namespace MentorLake.Gtk4.Gdk4;

public enum GdkCrossingMode
{
	GDK_CROSSING_NORMAL,
	GDK_CROSSING_GRAB,
	GDK_CROSSING_UNGRAB,
	GDK_CROSSING_GTK_GRAB,
	GDK_CROSSING_GTK_UNGRAB,
	GDK_CROSSING_STATE_CHANGED,
	GDK_CROSSING_TOUCH_BEGIN,
	GDK_CROSSING_TOUCH_END,
	GDK_CROSSING_DEVICE_SWITCH
}
