namespace MentorLake.Gtk4.Gdk4;

public enum GdkDeviceToolType
{
	GDK_DEVICE_TOOL_TYPE_UNKNOWN,
	GDK_DEVICE_TOOL_TYPE_PEN,
	GDK_DEVICE_TOOL_TYPE_ERASER,
	GDK_DEVICE_TOOL_TYPE_BRUSH,
	GDK_DEVICE_TOOL_TYPE_PENCIL,
	GDK_DEVICE_TOOL_TYPE_AIRBRUSH,
	GDK_DEVICE_TOOL_TYPE_MOUSE,
	GDK_DEVICE_TOOL_TYPE_LENS
}
