namespace MentorLake.Gtk4.Gdk4;

public enum GdkGLError
{
	GDK_GL_ERROR_NOT_AVAILABLE,
	GDK_GL_ERROR_UNSUPPORTED_FORMAT,
	GDK_GL_ERROR_UNSUPPORTED_PROFILE,
	GDK_GL_ERROR_COMPILATION_FAILED,
	GDK_GL_ERROR_LINK_FAILED
}
