namespace MentorLake.Gtk4.Gdk4;

public enum GdkGravity
{
	GDK_GRAVITY_NORTH_WEST,
	GDK_GRAVITY_NORTH,
	GDK_GRAVITY_NORTH_EAST,
	GDK_GRAVITY_WEST,
	GDK_GRAVITY_CENTER,
	GDK_GRAVITY_EAST,
	GDK_GRAVITY_SOUTH_WEST,
	GDK_GRAVITY_SOUTH,
	GDK_GRAVITY_SOUTH_EAST,
	GDK_GRAVITY_STATIC
}
