namespace MentorLake.Gtk4.Gdk4;

public enum GdkInputSource
{
	GDK_SOURCE_MOUSE,
	GDK_SOURCE_PEN,
	GDK_SOURCE_KEYBOARD,
	GDK_SOURCE_TOUCHSCREEN,
	GDK_SOURCE_TOUCHPAD,
	GDK_SOURCE_TRACKPOINT,
	GDK_SOURCE_TABLET_PAD
}
