namespace MentorLake.Gtk4.Gdk4;

public enum GdkNotifyType
{
	GDK_NOTIFY_ANCESTOR,
	GDK_NOTIFY_VIRTUAL,
	GDK_NOTIFY_INFERIOR,
	GDK_NOTIFY_NONLINEAR,
	GDK_NOTIFY_NONLINEAR_VIRTUAL,
	GDK_NOTIFY_UNKNOWN
}
