namespace MentorLake.Gtk4.Gdk4;

public enum GdkSurfaceEdge
{
	GDK_SURFACE_EDGE_NORTH_WEST,
	GDK_SURFACE_EDGE_NORTH,
	GDK_SURFACE_EDGE_NORTH_EAST,
	GDK_SURFACE_EDGE_WEST,
	GDK_SURFACE_EDGE_EAST,
	GDK_SURFACE_EDGE_SOUTH_WEST,
	GDK_SURFACE_EDGE_SOUTH,
	GDK_SURFACE_EDGE_SOUTH_EAST
}
