namespace MentorLake.Gtk4.Gdk4;

public enum GdkTextureError
{
	GDK_TEXTURE_ERROR_TOO_LARGE,
	GDK_TEXTURE_ERROR_CORRUPT_IMAGE,
	GDK_TEXTURE_ERROR_UNSUPPORTED_CONTENT,
	GDK_TEXTURE_ERROR_UNSUPPORTED_FORMAT
}
