namespace MentorLake.Gtk4.Gdk4;

public enum GdkTouchpadGesturePhase
{
	GDK_TOUCHPAD_GESTURE_PHASE_BEGIN,
	GDK_TOUCHPAD_GESTURE_PHASE_UPDATE,
	GDK_TOUCHPAD_GESTURE_PHASE_END,
	GDK_TOUCHPAD_GESTURE_PHASE_CANCEL
}
