namespace MentorLake.Gtk4.Gio;

[Flags]
public enum GAppInfoCreateFlags
{
	G_APP_INFO_CREATE_NONE = 0,
	G_APP_INFO_CREATE_NEEDS_TERMINAL = 1,
	G_APP_INFO_CREATE_SUPPORTS_URIS = 2,
	G_APP_INFO_CREATE_SUPPORTS_STARTUP_NOTIFICATION = 4
}
