namespace MentorLake.Gtk4.Gio;

[Flags]
public enum GAskPasswordFlags
{
	G_ASK_PASSWORD_NEED_PASSWORD = 0,
	G_ASK_PASSWORD_NEED_USERNAME = 1,
	G_ASK_PASSWORD_NEED_DOMAIN = 2,
	G_ASK_PASSWORD_SAVING_SUPPORTED = 4,
	G_ASK_PASSWORD_ANONYMOUS_SUPPORTED = 8,
	G_ASK_PASSWORD_TCRYPT = 16
}
