namespace MentorLake.Gtk4.Gio;

public enum GCredentialsType
{
	G_CREDENTIALS_TYPE_INVALID,
	G_CREDENTIALS_TYPE_LINUX_UCRED,
	G_CREDENTIALS_TYPE_FREEBSD_CMSGCRED,
	G_CREDENTIALS_TYPE_OPENBSD_SOCKPEERCRED,
	G_CREDENTIALS_TYPE_SOLARIS_UCRED,
	G_CREDENTIALS_TYPE_NETBSD_UNPCBID,
	G_CREDENTIALS_TYPE_APPLE_XUCRED,
	G_CREDENTIALS_TYPE_WIN32_PID
}
