namespace MentorLake.Gtk4.Gio;

public enum GDBusMessageType
{
	G_DBUS_MESSAGE_TYPE_INVALID,
	G_DBUS_MESSAGE_TYPE_METHOD_CALL,
	G_DBUS_MESSAGE_TYPE_METHOD_RETURN,
	G_DBUS_MESSAGE_TYPE_ERROR,
	G_DBUS_MESSAGE_TYPE_SIGNAL
}
