namespace MentorLake.Gtk4.Gio;

[Flags]
public enum GDBusMessageFlags
{
	G_DBUS_MESSAGE_FLAGS_NONE = 0,
	G_DBUS_MESSAGE_FLAGS_NO_REPLY_EXPECTED = 1,
	G_DBUS_MESSAGE_FLAGS_NO_AUTO_START = 2,
	G_DBUS_MESSAGE_FLAGS_ALLOW_INTERACTIVE_AUTHORIZATION = 4
}
