namespace MentorLake.Gtk4.Gio;

[Flags]
public enum GDBusConnectionFlags
{
	G_DBUS_CONNECTION_FLAGS_NONE = 0,
	G_DBUS_CONNECTION_FLAGS_AUTHENTICATION_CLIENT = 1,
	G_DBUS_CONNECTION_FLAGS_AUTHENTICATION_SERVER = 2,
	G_DBUS_CONNECTION_FLAGS_AUTHENTICATION_ALLOW_ANONYMOUS = 4,
	G_DBUS_CONNECTION_FLAGS_MESSAGE_BUS_CONNECTION = 8,
	G_DBUS_CONNECTION_FLAGS_DELAY_MESSAGE_PROCESSING = 16,
	G_DBUS_CONNECTION_FLAGS_AUTHENTICATION_REQUIRE_SAME_USER = 32,
	G_DBUS_CONNECTION_FLAGS_CROSS_NAMESPACE = 64
}
