namespace MentorLake.Gtk4.Gio;

[Flags]
public enum GDBusInterfaceSkeletonFlags
{
	G_DBUS_INTERFACE_SKELETON_FLAGS_NONE = 0,
	G_DBUS_INTERFACE_SKELETON_FLAGS_HANDLE_METHOD_INVOCATIONS_IN_THREAD = 1
}
