namespace MentorLake.Gtk4.Gio;

public enum GDriveStartStopType
{
	G_DRIVE_START_STOP_TYPE_UNKNOWN,
	G_DRIVE_START_STOP_TYPE_SHUTDOWN,
	G_DRIVE_START_STOP_TYPE_NETWORK,
	G_DRIVE_START_STOP_TYPE_MULTIDISK,
	G_DRIVE_START_STOP_TYPE_PASSWORD
}
