namespace MentorLake.Gtk4.Gio;

public enum GFileAttributeType
{
	G_FILE_ATTRIBUTE_TYPE_INVALID,
	G_FILE_ATTRIBUTE_TYPE_STRING,
	G_FILE_ATTRIBUTE_TYPE_BYTE_STRING,
	G_FILE_ATTRIBUTE_TYPE_BOOLEAN,
	G_FILE_ATTRIBUTE_TYPE_UINT32,
	G_FILE_ATTRIBUTE_TYPE_INT32,
	G_FILE_ATTRIBUTE_TYPE_UINT64,
	G_FILE_ATTRIBUTE_TYPE_INT64,
	G_FILE_ATTRIBUTE_TYPE_OBJECT,
	G_FILE_ATTRIBUTE_TYPE_STRINGV
}
