namespace MentorLake.Gtk4.Gio;

public enum GFileType
{
	G_FILE_TYPE_UNKNOWN,
	G_FILE_TYPE_REGULAR,
	G_FILE_TYPE_DIRECTORY,
	G_FILE_TYPE_SYMBOLIC_LINK,
	G_FILE_TYPE_SPECIAL,
	G_FILE_TYPE_SHORTCUT,
	G_FILE_TYPE_MOUNTABLE
}
