namespace MentorLake.Gtk4.Gio;

public enum GFileMonitorEvent
{
	G_FILE_MONITOR_EVENT_CHANGED,
	G_FILE_MONITOR_EVENT_CHANGES_DONE_HINT,
	G_FILE_MONITOR_EVENT_DELETED,
	G_FILE_MONITOR_EVENT_CREATED,
	G_FILE_MONITOR_EVENT_ATTRIBUTE_CHANGED,
	G_FILE_MONITOR_EVENT_PRE_UNMOUNT,
	G_FILE_MONITOR_EVENT_UNMOUNTED,
	G_FILE_MONITOR_EVENT_MOVED,
	G_FILE_MONITOR_EVENT_RENAMED,
	G_FILE_MONITOR_EVENT_MOVED_IN,
	G_FILE_MONITOR_EVENT_MOVED_OUT
}
