namespace MentorLake.Gtk4.Gio;

public enum GSocketClientEvent
{
	G_SOCKET_CLIENT_RESOLVING,
	G_SOCKET_CLIENT_RESOLVED,
	G_SOCKET_CLIENT_CONNECTING,
	G_SOCKET_CLIENT_CONNECTED,
	G_SOCKET_CLIENT_PROXY_NEGOTIATING,
	G_SOCKET_CLIENT_PROXY_NEGOTIATED,
	G_SOCKET_CLIENT_TLS_HANDSHAKING,
	G_SOCKET_CLIENT_TLS_HANDSHAKED,
	G_SOCKET_CLIENT_COMPLETE
}
