namespace MentorLake.Gtk4.Gio;

[Flags]
public enum GTlsPasswordFlags
{
	G_TLS_PASSWORD_NONE = 0,
	G_TLS_PASSWORD_RETRY = 1,
	G_TLS_PASSWORD_MANY_TRIES = 2,
	G_TLS_PASSWORD_FINAL_TRY = 4,
	G_TLS_PASSWORD_PKCS11_USER = 8,
	G_TLS_PASSWORD_PKCS11_SECURITY_OFFICER = 16,
	G_TLS_PASSWORD_PKCS11_CONTEXT_SPECIFIC = 32
}
