namespace MentorLake.Gtk4.Gio;

public enum GTlsProtocolVersion
{
	G_TLS_PROTOCOL_VERSION_UNKNOWN,
	G_TLS_PROTOCOL_VERSION_SSL_3_0,
	G_TLS_PROTOCOL_VERSION_TLS_1_0,
	G_TLS_PROTOCOL_VERSION_TLS_1_1,
	G_TLS_PROTOCOL_VERSION_TLS_1_2,
	G_TLS_PROTOCOL_VERSION_TLS_1_3,
	G_TLS_PROTOCOL_VERSION_DTLS_1_0,
	G_TLS_PROTOCOL_VERSION_DTLS_1_2
}
