namespace MentorLake.Gtk4.Gio;

public enum GTlsError
{
	G_TLS_ERROR_UNAVAILABLE,
	G_TLS_ERROR_MISC,
	G_TLS_ERROR_BAD_CERTIFICATE,
	G_TLS_ERROR_NOT_TLS,
	G_TLS_ERROR_HANDSHAKE,
	G_TLS_ERROR_CERTIFICATE_REQUIRED,
	G_TLS_ERROR_EOF,
	G_TLS_ERROR_INAPPROPRIATE_FALLBACK,
	G_TLS_ERROR_BAD_CERTIFICATE_PASSWORD
}
