namespace MentorLake.Gtk4.Gio;

public enum GUnixSocketAddressType
{
	G_UNIX_SOCKET_ADDRESS_INVALID,
	G_UNIX_SOCKET_ADDRESS_ANONYMOUS,
	G_UNIX_SOCKET_ADDRESS_PATH,
	G_UNIX_SOCKET_ADDRESS_ABSTRACT,
	G_UNIX_SOCKET_ADDRESS_ABSTRACT_PADDED
}
