namespace MentorLake.Gtk4.Cairo;

public enum cairo_antialias_t : uint
{
	CAIRO_ANTIALIAS_DEFAULT,
	CAIRO_ANTIALIAS_NONE,
	CAIRO_ANTIALIAS_GRAY,
	CAIRO_ANTIALIAS_SUBPIXEL,
	CAIRO_ANTIALIAS_FAST,
	CAIRO_ANTIALIAS_GOOD,
	CAIRO_ANTIALIAS_BEST
}
