namespace MentorLake.Gtk4.Cairo;

public enum cairo_device_type_t
{
	CAIRO_DEVICE_TYPE_DRM,
	CAIRO_DEVICE_TYPE_GL,
	CAIRO_DEVICE_TYPE_SCRIPT,
	CAIRO_DEVICE_TYPE_XCB,
	CAIRO_DEVICE_TYPE_XLIB,
	CAIRO_DEVICE_TYPE_XML,
	CAIRO_DEVICE_TYPE_COGL,
	CAIRO_DEVICE_TYPE_WIN32,
	CAIRO_DEVICE_TYPE_INVALID = -1
}
