namespace MentorLake.Gtk4.Cairo;

public enum cairo_pattern_type_t : uint
{
	CAIRO_PATTERN_TYPE_SOLID,
	CAIRO_PATTERN_TYPE_SURFACE,
	CAIRO_PATTERN_TYPE_LINEAR,
	CAIRO_PATTERN_TYPE_RADIAL,
	CAIRO_PATTERN_TYPE_MESH,
	CAIRO_PATTERN_TYPE_RASTER_SOURCE
}
