namespace MentorLake.Gtk4.Gdk;

public enum GdkCrossingMode : uint
{
	GDK_CROSSING_NORMAL,
	GDK_CROSSING_GRAB,
	GDK_CROSSING_UNGRAB,
	GDK_CROSSING_GTK_GRAB,
	GDK_CROSSING_GTK_UNGRAB,
	GDK_CROSSING_STATE_CHANGED,
	GDK_CROSSING_TOUCH_BEGIN,
	GDK_CROSSING_TOUCH_END,
	GDK_CROSSING_DEVICE_SWITCH
}

public enum GdkToplevelState : uint
{
	GDK_TOPLEVEL_STATE_MINIMIZED = 1 << 0,
	GDK_TOPLEVEL_STATE_MAXIMIZED = 1 << 1,
	GDK_TOPLEVEL_STATE_STICKY = 1 << 2,
	GDK_TOPLEVEL_STATE_FULLSCREEN = 1 << 3,
	GDK_TOPLEVEL_STATE_ABOVE = 1 << 4,
	GDK_TOPLEVEL_STATE_BELOW = 1 << 5,
	GDK_TOPLEVEL_STATE_FOCUSED = 1 << 6,
	GDK_TOPLEVEL_STATE_TILED = 1 << 7,
	GDK_TOPLEVEL_STATE_TOP_TILED = 1 << 8,
	GDK_TOPLEVEL_STATE_TOP_RESIZABLE = 1 << 9,
	GDK_TOPLEVEL_STATE_RIGHT_TILED = 1 << 10,
	GDK_TOPLEVEL_STATE_RIGHT_RESIZABLE = 1 << 11,
	GDK_TOPLEVEL_STATE_BOTTOM_TILED = 1 << 12,
	GDK_TOPLEVEL_STATE_BOTTOM_RESIZABLE = 1 << 13,
	GDK_TOPLEVEL_STATE_LEFT_TILED = 1 << 14,
	GDK_TOPLEVEL_STATE_LEFT_RESIZABLE = 1 << 15
}

public enum GdkDragCancelReason : uint
{
	GDK_DRAG_CANCEL_NO_TARGET,
	GDK_DRAG_CANCEL_USER_CANCELLED,
	GDK_DRAG_CANCEL_ERROR
}

public enum GdkKeyMatch : uint
{
	GDK_KEY_MATCH_NONE,
	GDK_KEY_MATCH_PARTIAL,
	GDK_KEY_MATCH_EXACT
}

public enum GdkTouchpadGesturePhase : uint
{
	GDK_TOUCHPAD_GESTURE_PHASE_BEGIN,
	GDK_TOUCHPAD_GESTURE_PHASE_UPDATE,
	GDK_TOUCHPAD_GESTURE_PHASE_END,
	GDK_TOUCHPAD_GESTURE_PHASE_CANCEL
}

public enum GdkNotifyType : uint
{
	GDK_NOTIFY_ANCESTOR = 0,
	GDK_NOTIFY_VIRTUAL = 1,
	GDK_NOTIFY_INFERIOR = 2,
	GDK_NOTIFY_NONLINEAR = 3,
	GDK_NOTIFY_NONLINEAR_VIRTUAL = 4,
	GDK_NOTIFY_UNKNOWN = 5
}

public enum GdkEventType : uint
{
	GDK_DELETE,
	GDK_MOTION_NOTIFY,
	GDK_BUTTON_PRESS,
	GDK_BUTTON_RELEASE,
	GDK_KEY_PRESS,
	GDK_KEY_RELEASE,
	GDK_ENTER_NOTIFY,
	GDK_LEAVE_NOTIFY,
	GDK_FOCUS_CHANGE,
	GDK_PROXIMITY_IN,
	GDK_PROXIMITY_OUT,
	GDK_DRAG_ENTER,
	GDK_DRAG_LEAVE,
	GDK_DRAG_MOTION,
	GDK_DROP_START,
	GDK_SCROLL,
	GDK_GRAB_BROKEN,
	GDK_TOUCH_BEGIN,
	GDK_TOUCH_UPDATE,
	GDK_TOUCH_END,
	GDK_TOUCH_CANCEL,
	GDK_TOUCHPAD_SWIPE,
	GDK_TOUCHPAD_PINCH,
	GDK_PAD_BUTTON_PRESS,
	GDK_PAD_BUTTON_RELEASE,
	GDK_PAD_RING,
	GDK_PAD_STRIP,
	GDK_PAD_GROUP_MODE,
	GDK_TOUCHPAD_HOLD,
	GDK_EVENT_LAST
}

public enum GdkAxisFlags : uint
{
	GDK_AXIS_FLAG_X = 1 << (int)GdkAxisUse.GDK_AXIS_X,
	GDK_AXIS_FLAG_Y = 1 << (int)GdkAxisUse.GDK_AXIS_Y,
	GDK_AXIS_FLAG_DELTA_X = 1 << (int)GdkAxisUse.GDK_AXIS_DELTA_X,
	GDK_AXIS_FLAG_DELTA_Y = 1 << (int)GdkAxisUse.GDK_AXIS_DELTA_Y,
	GDK_AXIS_FLAG_PRESSURE = 1 << (int)GdkAxisUse.GDK_AXIS_PRESSURE,
	GDK_AXIS_FLAG_XTILT = 1 << (int)GdkAxisUse.GDK_AXIS_XTILT,
	GDK_AXIS_FLAG_YTILT = 1 << (int)GdkAxisUse.GDK_AXIS_YTILT,
	GDK_AXIS_FLAG_WHEEL = 1 << (int)GdkAxisUse.GDK_AXIS_WHEEL,
	GDK_AXIS_FLAG_DISTANCE = 1 << (int)GdkAxisUse.GDK_AXIS_DISTANCE,
	GDK_AXIS_FLAG_ROTATION = 1 << (int)GdkAxisUse.GDK_AXIS_ROTATION,
	GDK_AXIS_FLAG_SLIDER = 1 << (int)GdkAxisUse.GDK_AXIS_SLIDER
}

public enum GdkSubpixelLayout : uint
{
	GDK_SUBPIXEL_LAYOUT_UNKNOWN,
	GDK_SUBPIXEL_LAYOUT_NONE,
	GDK_SUBPIXEL_LAYOUT_HORIZONTAL_RGB,
	GDK_SUBPIXEL_LAYOUT_HORIZONTAL_BGR,
	GDK_SUBPIXEL_LAYOUT_VERTICAL_RGB,
	GDK_SUBPIXEL_LAYOUT_VERTICAL_BGR
}

public enum GdkGravity : uint
{
	GDK_GRAVITY_NORTH_WEST = 1,
	GDK_GRAVITY_NORTH,
	GDK_GRAVITY_NORTH_EAST,
	GDK_GRAVITY_WEST,
	GDK_GRAVITY_CENTER,
	GDK_GRAVITY_EAST,
	GDK_GRAVITY_SOUTH_WEST,
	GDK_GRAVITY_SOUTH,
	GDK_GRAVITY_SOUTH_EAST,
	GDK_GRAVITY_STATIC
}

public enum GdkGLAPI : uint
{
	GDK_GL_API_GL = 1 << 0,
	GDK_GL_API_GLES = 1 << 1
}

public enum GdkFullscreenMode : uint
{
	GDK_FULLSCREEN_ON_CURRENT_MONITOR,
	GDK_FULLSCREEN_ON_ALL_MONITORS
}

public enum GdkPaintableFlags : uint
{
	GDK_PAINTABLE_STATIC_SIZE = 1 << 0,
	GDK_PAINTABLE_STATIC_CONTENTS = 1 << 1
}

public enum GdkGLError : uint
{
	GDK_GL_ERROR_NOT_AVAILABLE,
	GDK_GL_ERROR_UNSUPPORTED_FORMAT,
	GDK_GL_ERROR_UNSUPPORTED_PROFILE,
	GDK_GL_ERROR_COMPILATION_FAILED,
	GDK_GL_ERROR_LINK_FAILED
}

public enum GdkFrameClockPhase : uint
{
	GDK_FRAME_CLOCK_PHASE_NONE = 0,
	GDK_FRAME_CLOCK_PHASE_FLUSH_EVENTS = 1 << 0,
	GDK_FRAME_CLOCK_PHASE_BEFORE_PAINT = 1 << 1,
	GDK_FRAME_CLOCK_PHASE_UPDATE = 1 << 2,
	GDK_FRAME_CLOCK_PHASE_LAYOUT = 1 << 3,
	GDK_FRAME_CLOCK_PHASE_PAINT = 1 << 4,
	GDK_FRAME_CLOCK_PHASE_RESUME_EVENTS = 1 << 5,
	GDK_FRAME_CLOCK_PHASE_AFTER_PAINT = 1 << 6
}

public enum GdkScrollDirection : uint
{
	GDK_SCROLL_UP,
	GDK_SCROLL_DOWN,
	GDK_SCROLL_LEFT,
	GDK_SCROLL_RIGHT,
	GDK_SCROLL_SMOOTH
}

public enum GdkSeatCapabilities : uint
{
	GDK_SEAT_CAPABILITY_NONE = 0,
	GDK_SEAT_CAPABILITY_POINTER = 1 << 0,
	GDK_SEAT_CAPABILITY_TOUCH = 1 << 1,
	GDK_SEAT_CAPABILITY_TABLET_STYLUS = 1 << 2,
	GDK_SEAT_CAPABILITY_KEYBOARD = 1 << 3,
	GDK_SEAT_CAPABILITY_TABLET_PAD = 1 << 4,
	GDK_SEAT_CAPABILITY_ALL_POINTING = GDK_SEAT_CAPABILITY_POINTER | GDK_SEAT_CAPABILITY_TOUCH | GDK_SEAT_CAPABILITY_TABLET_STYLUS,
	GDK_SEAT_CAPABILITY_ALL = GDK_SEAT_CAPABILITY_ALL_POINTING | GDK_SEAT_CAPABILITY_KEYBOARD
}

public enum GdkSurfaceEdge : uint
{
	GDK_SURFACE_EDGE_NORTH_WEST,
	GDK_SURFACE_EDGE_NORTH,
	GDK_SURFACE_EDGE_NORTH_EAST,
	GDK_SURFACE_EDGE_WEST,
	GDK_SURFACE_EDGE_EAST,
	GDK_SURFACE_EDGE_SOUTH_WEST,
	GDK_SURFACE_EDGE_SOUTH,
	GDK_SURFACE_EDGE_SOUTH_EAST
}

public enum GdkDevicePadFeature : uint
{
	GDK_DEVICE_PAD_FEATURE_BUTTON,
	GDK_DEVICE_PAD_FEATURE_RING,
	GDK_DEVICE_PAD_FEATURE_STRIP
}

public enum GdkAxisUse : uint
{
	GDK_AXIS_IGNORE,
	GDK_AXIS_X,
	GDK_AXIS_Y,
	GDK_AXIS_DELTA_X,
	GDK_AXIS_DELTA_Y,
	GDK_AXIS_PRESSURE,
	GDK_AXIS_XTILT,
	GDK_AXIS_YTILT,
	GDK_AXIS_WHEEL,
	GDK_AXIS_DISTANCE,
	GDK_AXIS_ROTATION,
	GDK_AXIS_SLIDER,
	GDK_AXIS_LAST
}

public enum GdkInputSource : uint
{
	GDK_SOURCE_MOUSE,
	GDK_SOURCE_PEN,
	GDK_SOURCE_KEYBOARD,
	GDK_SOURCE_TOUCHSCREEN,
	GDK_SOURCE_TOUCHPAD,
	GDK_SOURCE_TRACKPOINT,
	GDK_SOURCE_TABLET_PAD
}

public enum GdkDeviceToolType : uint
{
	GDK_DEVICE_TOOL_TYPE_UNKNOWN,
	GDK_DEVICE_TOOL_TYPE_PEN,
	GDK_DEVICE_TOOL_TYPE_ERASER,
	GDK_DEVICE_TOOL_TYPE_BRUSH,
	GDK_DEVICE_TOOL_TYPE_PENCIL,
	GDK_DEVICE_TOOL_TYPE_AIRBRUSH,
	GDK_DEVICE_TOOL_TYPE_MOUSE,
	GDK_DEVICE_TOOL_TYPE_LENS
}

public enum GdkAnchorHints : uint
{
	GDK_ANCHOR_FLIP_X = 1 << 0,
	GDK_ANCHOR_FLIP_Y = 1 << 1,
	GDK_ANCHOR_SLIDE_X = 1 << 2,
	GDK_ANCHOR_SLIDE_Y = 1 << 3,
	GDK_ANCHOR_RESIZE_X = 1 << 4,
	GDK_ANCHOR_RESIZE_Y = 1 << 5,
	GDK_ANCHOR_FLIP = GDK_ANCHOR_FLIP_X | GDK_ANCHOR_FLIP_Y,
	GDK_ANCHOR_SLIDE = GDK_ANCHOR_SLIDE_X | GDK_ANCHOR_SLIDE_Y,
	GDK_ANCHOR_RESIZE = GDK_ANCHOR_RESIZE_X | GDK_ANCHOR_RESIZE_Y
}

public enum GdkTextureError : uint
{
	GDK_TEXTURE_ERROR_TOO_LARGE,
	GDK_TEXTURE_ERROR_CORRUPT_IMAGE,
	GDK_TEXTURE_ERROR_UNSUPPORTED_CONTENT,
	GDK_TEXTURE_ERROR_UNSUPPORTED_FORMAT
}

public enum GdkVulkanError : uint
{
	GDK_VULKAN_ERROR_UNSUPPORTED,
	GDK_VULKAN_ERROR_NOT_AVAILABLE
}

public enum GdkModifierType : uint
{
	GDK_SHIFT_MASK = 1 << 0,
	GDK_LOCK_MASK = 1 << 1,
	GDK_CONTROL_MASK = 1 << 2,
	GDK_ALT_MASK = 1 << 3,
	GDK_BUTTON1_MASK = 1 << 8,
	GDK_BUTTON2_MASK = 1 << 9,
	GDK_BUTTON3_MASK = 1 << 10,
	GDK_BUTTON4_MASK = 1 << 11,
	GDK_BUTTON5_MASK = 1 << 12,
	GDK_SUPER_MASK = 1 << 26,
	GDK_HYPER_MASK = 1 << 27,
	GDK_META_MASK = 1 << 28
}

public enum GdkTitlebarGesture : uint
{
	GDK_TITLEBAR_GESTURE_DOUBLE_CLICK = 1,
	GDK_TITLEBAR_GESTURE_RIGHT_CLICK = 2,
	GDK_TITLEBAR_GESTURE_MIDDLE_CLICK = 3
}

public enum GdkDragAction : uint
{
	GDK_ACTION_COPY = 1 << 0,
	GDK_ACTION_MOVE = 1 << 1,
	GDK_ACTION_LINK = 1 << 2,
	GDK_ACTION_ASK = 1 << 3
}

public enum GdkMemoryFormat : uint
{
	GDK_MEMORY_B8G8R8A8_PREMULTIPLIED,
	GDK_MEMORY_A8R8G8B8_PREMULTIPLIED,
	GDK_MEMORY_R8G8B8A8_PREMULTIPLIED,
	GDK_MEMORY_B8G8R8A8,
	GDK_MEMORY_A8R8G8B8,
	GDK_MEMORY_R8G8B8A8,
	GDK_MEMORY_A8B8G8R8,
	GDK_MEMORY_R8G8B8,
	GDK_MEMORY_B8G8R8,
	GDK_MEMORY_R16G16B16,
	GDK_MEMORY_R16G16B16A16_PREMULTIPLIED,
	GDK_MEMORY_R16G16B16A16,
	GDK_MEMORY_R16G16B16_FLOAT,
	GDK_MEMORY_R16G16B16A16_FLOAT_PREMULTIPLIED,
	GDK_MEMORY_R16G16B16A16_FLOAT,
	GDK_MEMORY_R32G32B32_FLOAT,
	GDK_MEMORY_R32G32B32A32_FLOAT_PREMULTIPLIED,
	GDK_MEMORY_R32G32B32A32_FLOAT,
	GDK_MEMORY_N_FORMATS
}
