namespace MentorLake.Gtk4.Gtk;

public enum GtkSortType : uint
{
	GTK_SORT_ASCENDING,
	GTK_SORT_DESCENDING
}

public enum GtkPolicyType : uint
{
	GTK_POLICY_ALWAYS,
	GTK_POLICY_AUTOMATIC,
	GTK_POLICY_NEVER,
	GTK_POLICY_EXTERNAL
}

public enum GtkPageOrientation : uint
{
	GTK_PAGE_ORIENTATION_PORTRAIT,
	GTK_PAGE_ORIENTATION_LANDSCAPE,
	GTK_PAGE_ORIENTATION_REVERSE_PORTRAIT,
	GTK_PAGE_ORIENTATION_REVERSE_LANDSCAPE
}

public enum GtkBaselinePosition : uint
{
	GTK_BASELINE_POSITION_TOP,
	GTK_BASELINE_POSITION_CENTER,
	GTK_BASELINE_POSITION_BOTTOM
}

public enum GtkEventSequenceState : uint
{
	GTK_EVENT_SEQUENCE_NONE,
	GTK_EVENT_SEQUENCE_CLAIMED,
	GTK_EVENT_SEQUENCE_DENIED
}

public enum GtkPrintPages : uint
{
	GTK_PRINT_PAGES_ALL,
	GTK_PRINT_PAGES_CURRENT,
	GTK_PRINT_PAGES_RANGES,
	GTK_PRINT_PAGES_SELECTION
}

public enum GtkLicense : uint
{
	GTK_LICENSE_UNKNOWN,
	GTK_LICENSE_CUSTOM,
	GTK_LICENSE_GPL_2_0,
	GTK_LICENSE_GPL_3_0,
	GTK_LICENSE_LGPL_2_1,
	GTK_LICENSE_LGPL_3_0,
	GTK_LICENSE_BSD,
	GTK_LICENSE_MIT_X11,
	GTK_LICENSE_ARTISTIC,
	GTK_LICENSE_GPL_2_0_ONLY,
	GTK_LICENSE_GPL_3_0_ONLY,
	GTK_LICENSE_LGPL_2_1_ONLY,
	GTK_LICENSE_LGPL_3_0_ONLY,
	GTK_LICENSE_AGPL_3_0,
	GTK_LICENSE_AGPL_3_0_ONLY,
	GTK_LICENSE_BSD_3,
	GTK_LICENSE_APACHE_2_0,
	GTK_LICENSE_MPL_2_0
}

public enum GtkTreeModelFlags : uint
{
	GTK_TREE_MODEL_ITERS_PERSIST = 1 << 0,
	GTK_TREE_MODEL_LIST_ONLY = 1 << 1
}

public enum GtkUnit : uint
{
	GTK_UNIT_NONE,
	GTK_UNIT_POINTS,
	GTK_UNIT_INCH,
	GTK_UNIT_MM
}

public enum GtkPanDirection : uint
{
	GTK_PAN_DIRECTION_LEFT,
	GTK_PAN_DIRECTION_RIGHT,
	GTK_PAN_DIRECTION_UP,
	GTK_PAN_DIRECTION_DOWN
}

public enum GtkRecentManagerError : uint
{
	GTK_RECENT_MANAGER_ERROR_NOT_FOUND,
	GTK_RECENT_MANAGER_ERROR_INVALID_URI,
	GTK_RECENT_MANAGER_ERROR_INVALID_ENCODING,
	GTK_RECENT_MANAGER_ERROR_NOT_REGISTERED,
	GTK_RECENT_MANAGER_ERROR_READ,
	GTK_RECENT_MANAGER_ERROR_WRITE,
	GTK_RECENT_MANAGER_ERROR_UNKNOWN
}

public enum GtkTreeViewDropPosition : uint
{
	GTK_TREE_VIEW_DROP_BEFORE,
	GTK_TREE_VIEW_DROP_AFTER,
	GTK_TREE_VIEW_DROP_INTO_OR_BEFORE,
	GTK_TREE_VIEW_DROP_INTO_OR_AFTER
}

public enum GtkAccessibleRole : uint
{
	GTK_ACCESSIBLE_ROLE_ALERT,
	GTK_ACCESSIBLE_ROLE_ALERT_DIALOG,
	GTK_ACCESSIBLE_ROLE_BANNER,
	GTK_ACCESSIBLE_ROLE_BUTTON,
	GTK_ACCESSIBLE_ROLE_CAPTION,
	GTK_ACCESSIBLE_ROLE_CELL,
	GTK_ACCESSIBLE_ROLE_CHECKBOX,
	GTK_ACCESSIBLE_ROLE_COLUMN_HEADER,
	GTK_ACCESSIBLE_ROLE_COMBO_BOX,
	GTK_ACCESSIBLE_ROLE_COMMAND,
	GTK_ACCESSIBLE_ROLE_COMPOSITE,
	GTK_ACCESSIBLE_ROLE_DIALOG,
	GTK_ACCESSIBLE_ROLE_DOCUMENT,
	GTK_ACCESSIBLE_ROLE_FEED,
	GTK_ACCESSIBLE_ROLE_FORM,
	GTK_ACCESSIBLE_ROLE_GENERIC,
	GTK_ACCESSIBLE_ROLE_GRID,
	GTK_ACCESSIBLE_ROLE_GRID_CELL,
	GTK_ACCESSIBLE_ROLE_GROUP,
	GTK_ACCESSIBLE_ROLE_HEADING,
	GTK_ACCESSIBLE_ROLE_IMG,
	GTK_ACCESSIBLE_ROLE_INPUT,
	GTK_ACCESSIBLE_ROLE_LABEL,
	GTK_ACCESSIBLE_ROLE_LANDMARK,
	GTK_ACCESSIBLE_ROLE_LEGEND,
	GTK_ACCESSIBLE_ROLE_LINK,
	GTK_ACCESSIBLE_ROLE_LIST,
	GTK_ACCESSIBLE_ROLE_LIST_BOX,
	GTK_ACCESSIBLE_ROLE_LIST_ITEM,
	GTK_ACCESSIBLE_ROLE_LOG,
	GTK_ACCESSIBLE_ROLE_MAIN,
	GTK_ACCESSIBLE_ROLE_MARQUEE,
	GTK_ACCESSIBLE_ROLE_MATH,
	GTK_ACCESSIBLE_ROLE_METER,
	GTK_ACCESSIBLE_ROLE_MENU,
	GTK_ACCESSIBLE_ROLE_MENU_BAR,
	GTK_ACCESSIBLE_ROLE_MENU_ITEM,
	GTK_ACCESSIBLE_ROLE_MENU_ITEM_CHECKBOX,
	GTK_ACCESSIBLE_ROLE_MENU_ITEM_RADIO,
	GTK_ACCESSIBLE_ROLE_NAVIGATION,
	GTK_ACCESSIBLE_ROLE_NONE,
	GTK_ACCESSIBLE_ROLE_NOTE,
	GTK_ACCESSIBLE_ROLE_OPTION,
	GTK_ACCESSIBLE_ROLE_PRESENTATION,
	GTK_ACCESSIBLE_ROLE_PROGRESS_BAR,
	GTK_ACCESSIBLE_ROLE_RADIO,
	GTK_ACCESSIBLE_ROLE_RADIO_GROUP,
	GTK_ACCESSIBLE_ROLE_RANGE,
	GTK_ACCESSIBLE_ROLE_REGION,
	GTK_ACCESSIBLE_ROLE_ROW,
	GTK_ACCESSIBLE_ROLE_ROW_GROUP,
	GTK_ACCESSIBLE_ROLE_ROW_HEADER,
	GTK_ACCESSIBLE_ROLE_SCROLLBAR,
	GTK_ACCESSIBLE_ROLE_SEARCH,
	GTK_ACCESSIBLE_ROLE_SEARCH_BOX,
	GTK_ACCESSIBLE_ROLE_SECTION,
	GTK_ACCESSIBLE_ROLE_SECTION_HEAD,
	GTK_ACCESSIBLE_ROLE_SELECT,
	GTK_ACCESSIBLE_ROLE_SEPARATOR,
	GTK_ACCESSIBLE_ROLE_SLIDER,
	GTK_ACCESSIBLE_ROLE_SPIN_BUTTON,
	GTK_ACCESSIBLE_ROLE_STATUS,
	GTK_ACCESSIBLE_ROLE_STRUCTURE,
	GTK_ACCESSIBLE_ROLE_SWITCH,
	GTK_ACCESSIBLE_ROLE_TAB,
	GTK_ACCESSIBLE_ROLE_TABLE,
	GTK_ACCESSIBLE_ROLE_TAB_LIST,
	GTK_ACCESSIBLE_ROLE_TAB_PANEL,
	GTK_ACCESSIBLE_ROLE_TEXT_BOX,
	GTK_ACCESSIBLE_ROLE_TIME,
	GTK_ACCESSIBLE_ROLE_TIMER,
	GTK_ACCESSIBLE_ROLE_TOOLBAR,
	GTK_ACCESSIBLE_ROLE_TOOLTIP,
	GTK_ACCESSIBLE_ROLE_TREE,
	GTK_ACCESSIBLE_ROLE_TREE_GRID,
	GTK_ACCESSIBLE_ROLE_TREE_ITEM,
	GTK_ACCESSIBLE_ROLE_WIDGET,
	GTK_ACCESSIBLE_ROLE_WINDOW
}

public enum GtkFontChooserLevel : uint
{
	GTK_FONT_CHOOSER_LEVEL_FAMILY = 0,
	GTK_FONT_CHOOSER_LEVEL_STYLE = 1 << 0,
	GTK_FONT_CHOOSER_LEVEL_SIZE = 1 << 1,
	GTK_FONT_CHOOSER_LEVEL_VARIATIONS = 1 << 2,
	GTK_FONT_CHOOSER_LEVEL_FEATURES = 1 << 3
}

public enum GtkTreeViewColumnSizing : uint
{
	GTK_TREE_VIEW_COLUMN_GROW_ONLY,
	GTK_TREE_VIEW_COLUMN_AUTOSIZE,
	GTK_TREE_VIEW_COLUMN_FIXED
}

public enum GtkButtonsType : uint
{
	GTK_BUTTONS_NONE,
	GTK_BUTTONS_OK,
	GTK_BUTTONS_CLOSE,
	GTK_BUTTONS_CANCEL,
	GTK_BUTTONS_YES_NO,
	GTK_BUTTONS_OK_CANCEL
}

public enum GtkPropagationPhase : uint
{
	GTK_PHASE_NONE,
	GTK_PHASE_CAPTURE,
	GTK_PHASE_BUBBLE,
	GTK_PHASE_TARGET
}

public enum GtkPrintDuplex : uint
{
	GTK_PRINT_DUPLEX_SIMPLEX,
	GTK_PRINT_DUPLEX_HORIZONTAL,
	GTK_PRINT_DUPLEX_VERTICAL
}

public enum GtkSizeRequestMode : uint
{
	GTK_SIZE_REQUEST_HEIGHT_FOR_WIDTH = 0,
	GTK_SIZE_REQUEST_WIDTH_FOR_HEIGHT,
	GTK_SIZE_REQUEST_CONSTANT_SIZE
}

public enum GtkApplicationInhibitFlags : uint
{
	GTK_APPLICATION_INHIBIT_LOGOUT = 1 << 0,
	GTK_APPLICATION_INHIBIT_SWITCH = 1 << 1,
	GTK_APPLICATION_INHIBIT_SUSPEND = 1 << 2,
	GTK_APPLICATION_INHIBIT_IDLE = 1 << 3
}

public enum GtkPageSet : uint
{
	GTK_PAGE_SET_ALL,
	GTK_PAGE_SET_EVEN,
	GTK_PAGE_SET_ODD
}

public enum GtkCellRendererState : uint
{
	GTK_CELL_RENDERER_SELECTED = 1 << 0,
	GTK_CELL_RENDERER_PRELIT = 1 << 1,
	GTK_CELL_RENDERER_INSENSITIVE = 1 << 2,
	GTK_CELL_RENDERER_SORTED = 1 << 3,
	GTK_CELL_RENDERER_FOCUSED = 1 << 4,
	GTK_CELL_RENDERER_EXPANDABLE = 1 << 5,
	GTK_CELL_RENDERER_EXPANDED = 1 << 6
}

public enum GtkAccessibleInvalidState : uint
{
	GTK_ACCESSIBLE_INVALID_FALSE,
	GTK_ACCESSIBLE_INVALID_TRUE,
	GTK_ACCESSIBLE_INVALID_GRAMMAR,
	GTK_ACCESSIBLE_INVALID_SPELLING
}

public enum GtkPackType : uint
{
	GTK_PACK_START,
	GTK_PACK_END
}

public enum GtkMessageType : uint
{
	GTK_MESSAGE_INFO,
	GTK_MESSAGE_WARNING,
	GTK_MESSAGE_QUESTION,
	GTK_MESSAGE_ERROR,
	GTK_MESSAGE_OTHER
}

public enum GtkInputPurpose : uint
{
	GTK_INPUT_PURPOSE_FREE_FORM,
	GTK_INPUT_PURPOSE_ALPHA,
	GTK_INPUT_PURPOSE_DIGITS,
	GTK_INPUT_PURPOSE_NUMBER,
	GTK_INPUT_PURPOSE_PHONE,
	GTK_INPUT_PURPOSE_URL,
	GTK_INPUT_PURPOSE_EMAIL,
	GTK_INPUT_PURPOSE_NAME,
	GTK_INPUT_PURPOSE_PASSWORD,
	GTK_INPUT_PURPOSE_PIN,
	GTK_INPUT_PURPOSE_TERMINAL
}

public enum GtkScrollType : uint
{
	GTK_SCROLL_NONE,
	GTK_SCROLL_JUMP,
	GTK_SCROLL_STEP_BACKWARD,
	GTK_SCROLL_STEP_FORWARD,
	GTK_SCROLL_PAGE_BACKWARD,
	GTK_SCROLL_PAGE_FORWARD,
	GTK_SCROLL_STEP_UP,
	GTK_SCROLL_STEP_DOWN,
	GTK_SCROLL_PAGE_UP,
	GTK_SCROLL_PAGE_DOWN,
	GTK_SCROLL_STEP_LEFT,
	GTK_SCROLL_STEP_RIGHT,
	GTK_SCROLL_PAGE_LEFT,
	GTK_SCROLL_PAGE_RIGHT,
	GTK_SCROLL_START,
	GTK_SCROLL_END
}

public enum GtkCellRendererAccelMode : uint
{
	GTK_CELL_RENDERER_ACCEL_MODE_GTK,
	GTK_CELL_RENDERER_ACCEL_MODE_OTHER
}

public enum GtkNumberUpLayout : uint
{
	GTK_NUMBER_UP_LAYOUT_LEFT_TO_RIGHT_TOP_TO_BOTTOM,
	GTK_NUMBER_UP_LAYOUT_LEFT_TO_RIGHT_BOTTOM_TO_TOP,
	GTK_NUMBER_UP_LAYOUT_RIGHT_TO_LEFT_TOP_TO_BOTTOM,
	GTK_NUMBER_UP_LAYOUT_RIGHT_TO_LEFT_BOTTOM_TO_TOP,
	GTK_NUMBER_UP_LAYOUT_TOP_TO_BOTTOM_LEFT_TO_RIGHT,
	GTK_NUMBER_UP_LAYOUT_TOP_TO_BOTTOM_RIGHT_TO_LEFT,
	GTK_NUMBER_UP_LAYOUT_BOTTOM_TO_TOP_LEFT_TO_RIGHT,
	GTK_NUMBER_UP_LAYOUT_BOTTOM_TO_TOP_RIGHT_TO_LEFT
}

public enum GtkIconViewDropPosition : uint
{
	GTK_ICON_VIEW_NO_DROP,
	GTK_ICON_VIEW_DROP_INTO,
	GTK_ICON_VIEW_DROP_LEFT,
	GTK_ICON_VIEW_DROP_RIGHT,
	GTK_ICON_VIEW_DROP_ABOVE,
	GTK_ICON_VIEW_DROP_BELOW
}

public enum GtkWrapMode : uint
{
	GTK_WRAP_NONE,
	GTK_WRAP_CHAR,
	GTK_WRAP_WORD,
	GTK_WRAP_WORD_CHAR
}

public enum GtkSorterOrder : uint
{
	GTK_SORTER_ORDER_PARTIAL,
	GTK_SORTER_ORDER_NONE,
	GTK_SORTER_ORDER_TOTAL
}

public enum GtkCssParserWarning : uint
{
	GTK_CSS_PARSER_WARNING_DEPRECATED,
	GTK_CSS_PARSER_WARNING_SYNTAX,
	GTK_CSS_PARSER_WARNING_UNIMPLEMENTED
}

public enum GtkPickFlags : uint
{
	GTK_PICK_DEFAULT = 0,
	GTK_PICK_INSENSITIVE = 1 << 0,
	GTK_PICK_NON_TARGETABLE = 1 << 1
}

public enum GtkFilterChange : uint
{
	GTK_FILTER_CHANGE_DIFFERENT = 0,
	GTK_FILTER_CHANGE_LESS_STRICT,
	GTK_FILTER_CHANGE_MORE_STRICT
}

public enum GtkFileChooserAction : uint
{
	GTK_FILE_CHOOSER_ACTION_OPEN,
	GTK_FILE_CHOOSER_ACTION_SAVE,
	GTK_FILE_CHOOSER_ACTION_SELECT_FOLDER
}

public enum GtkAccessibleState : uint
{
	GTK_ACCESSIBLE_STATE_BUSY,
	GTK_ACCESSIBLE_STATE_CHECKED,
	GTK_ACCESSIBLE_STATE_DISABLED,
	GTK_ACCESSIBLE_STATE_EXPANDED,
	GTK_ACCESSIBLE_STATE_HIDDEN,
	GTK_ACCESSIBLE_STATE_INVALID,
	GTK_ACCESSIBLE_STATE_PRESSED,
	GTK_ACCESSIBLE_STATE_SELECTED
}

public enum GtkStateFlags : uint
{
	GTK_STATE_FLAG_NORMAL = 0,
	GTK_STATE_FLAG_ACTIVE = 1 << 0,
	GTK_STATE_FLAG_PRELIGHT = 1 << 1,
	GTK_STATE_FLAG_SELECTED = 1 << 2,
	GTK_STATE_FLAG_INSENSITIVE = 1 << 3,
	GTK_STATE_FLAG_INCONSISTENT = 1 << 4,
	GTK_STATE_FLAG_FOCUSED = 1 << 5,
	GTK_STATE_FLAG_BACKDROP = 1 << 6,
	GTK_STATE_FLAG_DIR_LTR = 1 << 7,
	GTK_STATE_FLAG_DIR_RTL = 1 << 8,
	GTK_STATE_FLAG_LINK = 1 << 9,
	GTK_STATE_FLAG_VISITED = 1 << 10,
	GTK_STATE_FLAG_CHECKED = 1 << 11,
	GTK_STATE_FLAG_DROP_ACTIVE = 1 << 12,
	GTK_STATE_FLAG_FOCUS_VISIBLE = 1 << 13,
	GTK_STATE_FLAG_FOCUS_WITHIN = 1 << 14
}

public enum GtkTextViewLayer : uint
{
	GTK_TEXT_VIEW_LAYER_BELOW_TEXT,
	GTK_TEXT_VIEW_LAYER_ABOVE_TEXT
}

public enum GtkPrintError : uint
{
	GTK_PRINT_ERROR_GENERAL,
	GTK_PRINT_ERROR_INTERNAL_ERROR,
	GTK_PRINT_ERROR_NOMEM,
	GTK_PRINT_ERROR_INVALID_FILE
}

public enum GtkIconThemeError : uint
{
	GTK_ICON_THEME_NOT_FOUND,
	GTK_ICON_THEME_FAILED
}

public enum GtkStackTransitionType : uint
{
	GTK_STACK_TRANSITION_TYPE_NONE,
	GTK_STACK_TRANSITION_TYPE_CROSSFADE,
	GTK_STACK_TRANSITION_TYPE_SLIDE_RIGHT,
	GTK_STACK_TRANSITION_TYPE_SLIDE_LEFT,
	GTK_STACK_TRANSITION_TYPE_SLIDE_UP,
	GTK_STACK_TRANSITION_TYPE_SLIDE_DOWN,
	GTK_STACK_TRANSITION_TYPE_SLIDE_LEFT_RIGHT,
	GTK_STACK_TRANSITION_TYPE_SLIDE_UP_DOWN,
	GTK_STACK_TRANSITION_TYPE_OVER_UP,
	GTK_STACK_TRANSITION_TYPE_OVER_DOWN,
	GTK_STACK_TRANSITION_TYPE_OVER_LEFT,
	GTK_STACK_TRANSITION_TYPE_OVER_RIGHT,
	GTK_STACK_TRANSITION_TYPE_UNDER_UP,
	GTK_STACK_TRANSITION_TYPE_UNDER_DOWN,
	GTK_STACK_TRANSITION_TYPE_UNDER_LEFT,
	GTK_STACK_TRANSITION_TYPE_UNDER_RIGHT,
	GTK_STACK_TRANSITION_TYPE_OVER_UP_DOWN,
	GTK_STACK_TRANSITION_TYPE_OVER_DOWN_UP,
	GTK_STACK_TRANSITION_TYPE_OVER_LEFT_RIGHT,
	GTK_STACK_TRANSITION_TYPE_OVER_RIGHT_LEFT,
	GTK_STACK_TRANSITION_TYPE_ROTATE_LEFT,
	GTK_STACK_TRANSITION_TYPE_ROTATE_RIGHT,
	GTK_STACK_TRANSITION_TYPE_ROTATE_LEFT_RIGHT
}

public enum GtkMovementStep : uint
{
	GTK_MOVEMENT_LOGICAL_POSITIONS,
	GTK_MOVEMENT_VISUAL_POSITIONS,
	GTK_MOVEMENT_WORDS,
	GTK_MOVEMENT_DISPLAY_LINES,
	GTK_MOVEMENT_DISPLAY_LINE_ENDS,
	GTK_MOVEMENT_PARAGRAPHS,
	GTK_MOVEMENT_PARAGRAPH_ENDS,
	GTK_MOVEMENT_PAGES,
	GTK_MOVEMENT_BUFFER_ENDS,
	GTK_MOVEMENT_HORIZONTAL_PAGES
}

public enum GtkNaturalWrapMode : uint
{
	GTK_NATURAL_WRAP_INHERIT,
	GTK_NATURAL_WRAP_NONE,
	GTK_NATURAL_WRAP_WORD
}

public enum GtkShortcutType : uint
{
	GTK_SHORTCUT_ACCELERATOR,
	GTK_SHORTCUT_GESTURE_PINCH,
	GTK_SHORTCUT_GESTURE_STRETCH,
	GTK_SHORTCUT_GESTURE_ROTATE_CLOCKWISE,
	GTK_SHORTCUT_GESTURE_ROTATE_COUNTERCLOCKWISE,
	GTK_SHORTCUT_GESTURE_TWO_FINGER_SWIPE_LEFT,
	GTK_SHORTCUT_GESTURE_TWO_FINGER_SWIPE_RIGHT,
	GTK_SHORTCUT_GESTURE,
	GTK_SHORTCUT_GESTURE_SWIPE_LEFT,
	GTK_SHORTCUT_GESTURE_SWIPE_RIGHT
}

public enum GtkSpinType : uint
{
	GTK_SPIN_STEP_FORWARD,
	GTK_SPIN_STEP_BACKWARD,
	GTK_SPIN_PAGE_FORWARD,
	GTK_SPIN_PAGE_BACKWARD,
	GTK_SPIN_HOME,
	GTK_SPIN_END,
	GTK_SPIN_USER_DEFINED
}

public enum GtkFilterMatch : uint
{
	GTK_FILTER_MATCH_SOME = 0,
	GTK_FILTER_MATCH_NONE,
	GTK_FILTER_MATCH_ALL
}

public enum GtkNotebookTab : uint
{
	GTK_NOTEBOOK_TAB_FIRST,
	GTK_NOTEBOOK_TAB_LAST
}

public enum GtkDebugFlags : uint
{
	GTK_DEBUG_TEXT = 1 << 0,
	GTK_DEBUG_TREE = 1 << 1,
	GTK_DEBUG_KEYBINDINGS = 1 << 2,
	GTK_DEBUG_MODULES = 1 << 3,
	GTK_DEBUG_GEOMETRY = 1 << 4,
	GTK_DEBUG_ICONTHEME = 1 << 5,
	GTK_DEBUG_PRINTING = 1 << 6,
	GTK_DEBUG_BUILDER = 1 << 7,
	GTK_DEBUG_SIZE_REQUEST = 1 << 8,
	GTK_DEBUG_NO_CSS_CACHE = 1 << 9,
	GTK_DEBUG_INTERACTIVE = 1 << 10,
	GTK_DEBUG_TOUCHSCREEN = 1 << 11,
	GTK_DEBUG_ACTIONS = 1 << 12,
	GTK_DEBUG_LAYOUT = 1 << 13,
	GTK_DEBUG_SNAPSHOT = 1 << 14,
	GTK_DEBUG_CONSTRAINTS = 1 << 15,
	GTK_DEBUG_BUILDER_OBJECTS = 1 << 16,
	GTK_DEBUG_A11Y = 1 << 17,
	GTK_DEBUG_ICONFALLBACK = 1 << 18
}

public enum GtkStringFilterMatchMode : uint
{
	GTK_STRING_FILTER_MATCH_MODE_EXACT,
	GTK_STRING_FILTER_MATCH_MODE_SUBSTRING,
	GTK_STRING_FILTER_MATCH_MODE_PREFIX
}

public enum GtkSizeGroupMode : uint
{
	GTK_SIZE_GROUP_NONE,
	GTK_SIZE_GROUP_HORIZONTAL,
	GTK_SIZE_GROUP_VERTICAL,
	GTK_SIZE_GROUP_BOTH
}

public enum GtkPositionType : uint
{
	GTK_POS_LEFT,
	GTK_POS_RIGHT,
	GTK_POS_TOP,
	GTK_POS_BOTTOM
}

public enum GtkIconLookupFlags : uint
{
	GTK_ICON_LOOKUP_FORCE_REGULAR = 1 << 0,
	GTK_ICON_LOOKUP_FORCE_SYMBOLIC = 1 << 1,
	GTK_ICON_LOOKUP_PRELOAD = 1 << 2
}

public enum GtkAccessibleAutocomplete : uint
{
	GTK_ACCESSIBLE_AUTOCOMPLETE_NONE,
	GTK_ACCESSIBLE_AUTOCOMPLETE_INLINE,
	GTK_ACCESSIBLE_AUTOCOMPLETE_LIST,
	GTK_ACCESSIBLE_AUTOCOMPLETE_BOTH
}

public enum GtkSelectionMode : uint
{
	GTK_SELECTION_NONE,
	GTK_SELECTION_SINGLE,
	GTK_SELECTION_BROWSE,
	GTK_SELECTION_MULTIPLE
}

public enum GtkTextSearchFlags : uint
{
	GTK_TEXT_SEARCH_VISIBLE_ONLY = 1 << 0,
	GTK_TEXT_SEARCH_TEXT_ONLY = 1 << 1,
	GTK_TEXT_SEARCH_CASE_INSENSITIVE = 1 << 2
}

public enum GtkCornerType : uint
{
	GTK_CORNER_TOP_LEFT,
	GTK_CORNER_BOTTOM_LEFT,
	GTK_CORNER_TOP_RIGHT,
	GTK_CORNER_BOTTOM_RIGHT
}

public enum GtkImageType : uint
{
	GTK_IMAGE_EMPTY,
	GTK_IMAGE_ICON_NAME,
	GTK_IMAGE_GICON,
	GTK_IMAGE_PAINTABLE
}

public enum GtkEntryIconPosition : uint
{
	GTK_ENTRY_ICON_PRIMARY,
	GTK_ENTRY_ICON_SECONDARY
}

public enum GtkAccessibleSort : uint
{
	GTK_ACCESSIBLE_SORT_NONE,
	GTK_ACCESSIBLE_SORT_ASCENDING,
	GTK_ACCESSIBLE_SORT_DESCENDING,
	GTK_ACCESSIBLE_SORT_OTHER
}

public enum GtkSystemSetting : uint
{
	GTK_SYSTEM_SETTING_DPI,
	GTK_SYSTEM_SETTING_FONT_NAME,
	GTK_SYSTEM_SETTING_FONT_CONFIG,
	GTK_SYSTEM_SETTING_DISPLAY,
	GTK_SYSTEM_SETTING_ICON_THEME
}

public enum GtkPrintOperationResult : uint
{
	GTK_PRINT_OPERATION_RESULT_ERROR,
	GTK_PRINT_OPERATION_RESULT_APPLY,
	GTK_PRINT_OPERATION_RESULT_CANCEL,
	GTK_PRINT_OPERATION_RESULT_IN_PROGRESS
}

public enum GtkPopoverMenuFlags : uint
{
	GTK_POPOVER_MENU_NESTED = 1 << 0
}

public enum GtkPrintOperationAction : uint
{
	GTK_PRINT_OPERATION_ACTION_PRINT_DIALOG,
	GTK_PRINT_OPERATION_ACTION_PRINT,
	GTK_PRINT_OPERATION_ACTION_PREVIEW,
	GTK_PRINT_OPERATION_ACTION_EXPORT
}

public enum GtkInputHints : uint
{
	GTK_INPUT_HINT_NONE = 0,
	GTK_INPUT_HINT_SPELLCHECK = 1 << 0,
	GTK_INPUT_HINT_NO_SPELLCHECK = 1 << 1,
	GTK_INPUT_HINT_WORD_COMPLETION = 1 << 2,
	GTK_INPUT_HINT_LOWERCASE = 1 << 3,
	GTK_INPUT_HINT_UPPERCASE_CHARS = 1 << 4,
	GTK_INPUT_HINT_UPPERCASE_WORDS = 1 << 5,
	GTK_INPUT_HINT_UPPERCASE_SENTENCES = 1 << 6,
	GTK_INPUT_HINT_INHIBIT_OSK = 1 << 7,
	GTK_INPUT_HINT_VERTICAL_WRITING = 1 << 8,
	GTK_INPUT_HINT_EMOJI = 1 << 9,
	GTK_INPUT_HINT_NO_EMOJI = 1 << 10,
	GTK_INPUT_HINT_PRIVATE = 1 << 11
}

public enum GtkAlign : uint
{
	GTK_ALIGN_FILL,
	GTK_ALIGN_START,
	GTK_ALIGN_END,
	GTK_ALIGN_CENTER,
	GTK_ALIGN_BASELINE
}

public enum GtkFileChooserError : uint
{
	GTK_FILE_CHOOSER_ERROR_NONEXISTENT,
	GTK_FILE_CHOOSER_ERROR_BAD_FILENAME,
	GTK_FILE_CHOOSER_ERROR_ALREADY_EXISTS,
	GTK_FILE_CHOOSER_ERROR_INCOMPLETE_HOSTNAME
}

public enum GtkTextDirection : uint
{
	GTK_TEXT_DIR_NONE,
	GTK_TEXT_DIR_LTR,
	GTK_TEXT_DIR_RTL
}

public enum GtkSorterChange : uint
{
	GTK_SORTER_CHANGE_DIFFERENT,
	GTK_SORTER_CHANGE_INVERTED,
	GTK_SORTER_CHANGE_LESS_STRICT,
	GTK_SORTER_CHANGE_MORE_STRICT
}

public enum GtkPrintStatus : uint
{
	GTK_PRINT_STATUS_INITIAL,
	GTK_PRINT_STATUS_PREPARING,
	GTK_PRINT_STATUS_GENERATING_DATA,
	GTK_PRINT_STATUS_SENDING_DATA,
	GTK_PRINT_STATUS_PENDING,
	GTK_PRINT_STATUS_PENDING_ISSUE,
	GTK_PRINT_STATUS_PRINTING,
	GTK_PRINT_STATUS_FINISHED,
	GTK_PRINT_STATUS_FINISHED_ABORTED
}

public enum GtkPrintQuality : uint
{
	GTK_PRINT_QUALITY_LOW,
	GTK_PRINT_QUALITY_NORMAL,
	GTK_PRINT_QUALITY_HIGH,
	GTK_PRINT_QUALITY_DRAFT
}

public enum GtkShortcutScope : uint
{
	GTK_SHORTCUT_SCOPE_LOCAL,
	GTK_SHORTCUT_SCOPE_MANAGED,
	GTK_SHORTCUT_SCOPE_GLOBAL
}

public enum GtkPadActionType : uint
{
	GTK_PAD_ACTION_BUTTON,
	GTK_PAD_ACTION_RING,
	GTK_PAD_ACTION_STRIP
}

public enum GtkEditableProperties : uint
{
	GTK_EDITABLE_PROP_TEXT,
	GTK_EDITABLE_PROP_CURSOR_POSITION,
	GTK_EDITABLE_PROP_SELECTION_BOUND,
	GTK_EDITABLE_PROP_EDITABLE,
	GTK_EDITABLE_PROP_WIDTH_CHARS,
	GTK_EDITABLE_PROP_MAX_WIDTH_CHARS,
	GTK_EDITABLE_PROP_XALIGN,
	GTK_EDITABLE_PROP_ENABLE_UNDO,
	GTK_EDITABLE_NUM_PROPERTIES
}

public enum GtkScrollStep : uint
{
	GTK_SCROLL_STEPS,
	GTK_SCROLL_PAGES,
	GTK_SCROLL_ENDS,
	GTK_SCROLL_HORIZONTAL_STEPS,
	GTK_SCROLL_HORIZONTAL_PAGES,
	GTK_SCROLL_HORIZONTAL_ENDS
}

public enum GtkIconSize : uint
{
	GTK_ICON_SIZE_INHERIT,
	GTK_ICON_SIZE_NORMAL,
	GTK_ICON_SIZE_LARGE
}

public enum GtkOverflow : uint
{
	GTK_OVERFLOW_VISIBLE,
	GTK_OVERFLOW_HIDDEN
}

public enum GtkOrientation : uint
{
	GTK_ORIENTATION_HORIZONTAL,
	GTK_ORIENTATION_VERTICAL
}

public enum GtkCellRendererMode : uint
{
	GTK_CELL_RENDERER_MODE_INERT,
	GTK_CELL_RENDERER_MODE_ACTIVATABLE,
	GTK_CELL_RENDERER_MODE_EDITABLE
}

public enum GtkLevelBarMode : uint
{
	GTK_LEVEL_BAR_MODE_CONTINUOUS,
	GTK_LEVEL_BAR_MODE_DISCRETE
}

public enum GtkResponseType
{
	GTK_RESPONSE_NONE = -1,
	GTK_RESPONSE_REJECT = -2,
	GTK_RESPONSE_ACCEPT = -3,
	GTK_RESPONSE_DELETE_EVENT = -4,
	GTK_RESPONSE_OK = -5,
	GTK_RESPONSE_CANCEL = -6,
	GTK_RESPONSE_CLOSE = -7,
	GTK_RESPONSE_YES = -8,
	GTK_RESPONSE_NO = -9,
	GTK_RESPONSE_APPLY = -10,
	GTK_RESPONSE_HELP = -11
}

public enum GtkDirectionType : uint
{
	GTK_DIR_TAB_FORWARD,
	GTK_DIR_TAB_BACKWARD,
	GTK_DIR_UP,
	GTK_DIR_DOWN,
	GTK_DIR_LEFT,
	GTK_DIR_RIGHT
}

public enum GtkStyleContextPrintFlags : uint
{
	GTK_STYLE_CONTEXT_PRINT_NONE = 0,
	GTK_STYLE_CONTEXT_PRINT_RECURSE = 1 << 0,
	GTK_STYLE_CONTEXT_PRINT_SHOW_STYLE = 1 << 1,
	GTK_STYLE_CONTEXT_PRINT_SHOW_CHANGE = 1 << 2
}

public enum GtkAssistantPageType : uint
{
	GTK_ASSISTANT_PAGE_CONTENT,
	GTK_ASSISTANT_PAGE_INTRO,
	GTK_ASSISTANT_PAGE_CONFIRM,
	GTK_ASSISTANT_PAGE_SUMMARY,
	GTK_ASSISTANT_PAGE_PROGRESS,
	GTK_ASSISTANT_PAGE_CUSTOM
}

public enum GtkJustification : uint
{
	GTK_JUSTIFY_LEFT,
	GTK_JUSTIFY_RIGHT,
	GTK_JUSTIFY_CENTER,
	GTK_JUSTIFY_FILL
}

public enum GtkTextExtendSelection : uint
{
	GTK_TEXT_EXTEND_SELECTION_WORD,
	GTK_TEXT_EXTEND_SELECTION_LINE
}

public enum GtkSensitivityType : uint
{
	GTK_SENSITIVITY_AUTO,
	GTK_SENSITIVITY_ON,
	GTK_SENSITIVITY_OFF
}

public enum GtkTreeViewGridLines : uint
{
	GTK_TREE_VIEW_GRID_LINES_NONE,
	GTK_TREE_VIEW_GRID_LINES_HORIZONTAL,
	GTK_TREE_VIEW_GRID_LINES_VERTICAL,
	GTK_TREE_VIEW_GRID_LINES_BOTH
}

public enum GtkOrdering
{
	GTK_ORDERING_SMALLER = -1,
	GTK_ORDERING_EQUAL = 0,
	GTK_ORDERING_LARGER = 1
}

public enum GtkBuilderError : uint
{
	GTK_BUILDER_ERROR_INVALID_TYPE_FUNCTION,
	GTK_BUILDER_ERROR_UNHANDLED_TAG,
	GTK_BUILDER_ERROR_MISSING_ATTRIBUTE,
	GTK_BUILDER_ERROR_INVALID_ATTRIBUTE,
	GTK_BUILDER_ERROR_INVALID_TAG,
	GTK_BUILDER_ERROR_MISSING_PROPERTY_VALUE,
	GTK_BUILDER_ERROR_INVALID_VALUE,
	GTK_BUILDER_ERROR_VERSION_MISMATCH,
	GTK_BUILDER_ERROR_DUPLICATE_ID,
	GTK_BUILDER_ERROR_OBJECT_TYPE_REFUSED,
	GTK_BUILDER_ERROR_TEMPLATE_MISMATCH,
	GTK_BUILDER_ERROR_INVALID_PROPERTY,
	GTK_BUILDER_ERROR_INVALID_SIGNAL,
	GTK_BUILDER_ERROR_INVALID_ID,
	GTK_BUILDER_ERROR_INVALID_FUNCTION
}

public enum GtkShortcutActionFlags : uint
{
	GTK_SHORTCUT_ACTION_EXCLUSIVE = 1 << 0
}

public enum GtkEventControllerScrollFlags : uint
{
	GTK_EVENT_CONTROLLER_SCROLL_NONE = 0,
	GTK_EVENT_CONTROLLER_SCROLL_VERTICAL = 1 << 0,
	GTK_EVENT_CONTROLLER_SCROLL_HORIZONTAL = 1 << 1,
	GTK_EVENT_CONTROLLER_SCROLL_DISCRETE = 1 << 2,
	GTK_EVENT_CONTROLLER_SCROLL_KINETIC = 1 << 3,
	GTK_EVENT_CONTROLLER_SCROLL_BOTH_AXES = GTK_EVENT_CONTROLLER_SCROLL_VERTICAL | GTK_EVENT_CONTROLLER_SCROLL_HORIZONTAL
}

public enum GtkCssParserError : uint
{
	GTK_CSS_PARSER_ERROR_FAILED,
	GTK_CSS_PARSER_ERROR_SYNTAX,
	GTK_CSS_PARSER_ERROR_IMPORT,
	GTK_CSS_PARSER_ERROR_NAME,
	GTK_CSS_PARSER_ERROR_UNKNOWN_VALUE
}

public enum GtkConstraintStrength : uint
{
	GTK_CONSTRAINT_STRENGTH_REQUIRED = 1001001000,
	GTK_CONSTRAINT_STRENGTH_STRONG = 1000000000,
	GTK_CONSTRAINT_STRENGTH_MEDIUM = 1000,
	GTK_CONSTRAINT_STRENGTH_WEAK = 1
}

public enum GtkSpinButtonUpdatePolicy : uint
{
	GTK_UPDATE_ALWAYS,
	GTK_UPDATE_IF_VALID
}

public enum GtkAccessibleTristate : uint
{
	GTK_ACCESSIBLE_TRISTATE_FALSE,
	GTK_ACCESSIBLE_TRISTATE_TRUE,
	GTK_ACCESSIBLE_TRISTATE_MIXED
}

public enum GtkArrowType : uint
{
	GTK_ARROW_UP,
	GTK_ARROW_DOWN,
	GTK_ARROW_LEFT,
	GTK_ARROW_RIGHT,
	GTK_ARROW_NONE
}

public enum GtkDialogFlags : uint
{
	GTK_DIALOG_MODAL = 1 << 0,
	GTK_DIALOG_DESTROY_WITH_PARENT = 1 << 1,
	GTK_DIALOG_USE_HEADER_BAR = 1 << 2
}

public enum GtkAccessibleRelation : uint
{
	GTK_ACCESSIBLE_RELATION_ACTIVE_DESCENDANT,
	GTK_ACCESSIBLE_RELATION_COL_COUNT,
	GTK_ACCESSIBLE_RELATION_COL_INDEX,
	GTK_ACCESSIBLE_RELATION_COL_INDEX_TEXT,
	GTK_ACCESSIBLE_RELATION_COL_SPAN,
	GTK_ACCESSIBLE_RELATION_CONTROLS,
	GTK_ACCESSIBLE_RELATION_DESCRIBED_BY,
	GTK_ACCESSIBLE_RELATION_DETAILS,
	GTK_ACCESSIBLE_RELATION_ERROR_MESSAGE,
	GTK_ACCESSIBLE_RELATION_FLOW_TO,
	GTK_ACCESSIBLE_RELATION_LABELLED_BY,
	GTK_ACCESSIBLE_RELATION_OWNS,
	GTK_ACCESSIBLE_RELATION_POS_IN_SET,
	GTK_ACCESSIBLE_RELATION_ROW_COUNT,
	GTK_ACCESSIBLE_RELATION_ROW_INDEX,
	GTK_ACCESSIBLE_RELATION_ROW_INDEX_TEXT,
	GTK_ACCESSIBLE_RELATION_ROW_SPAN,
	GTK_ACCESSIBLE_RELATION_SET_SIZE
}

public enum GtkConstraintAttribute : uint
{
	GTK_CONSTRAINT_ATTRIBUTE_NONE,
	GTK_CONSTRAINT_ATTRIBUTE_LEFT,
	GTK_CONSTRAINT_ATTRIBUTE_RIGHT,
	GTK_CONSTRAINT_ATTRIBUTE_TOP,
	GTK_CONSTRAINT_ATTRIBUTE_BOTTOM,
	GTK_CONSTRAINT_ATTRIBUTE_START,
	GTK_CONSTRAINT_ATTRIBUTE_END,
	GTK_CONSTRAINT_ATTRIBUTE_WIDTH,
	GTK_CONSTRAINT_ATTRIBUTE_HEIGHT,
	GTK_CONSTRAINT_ATTRIBUTE_CENTER_X,
	GTK_CONSTRAINT_ATTRIBUTE_CENTER_Y,
	GTK_CONSTRAINT_ATTRIBUTE_BASELINE
}

public enum GtkConstraintVflParserError : uint
{
	GTK_CONSTRAINT_VFL_PARSER_ERROR_INVALID_SYMBOL,
	GTK_CONSTRAINT_VFL_PARSER_ERROR_INVALID_ATTRIBUTE,
	GTK_CONSTRAINT_VFL_PARSER_ERROR_INVALID_VIEW,
	GTK_CONSTRAINT_VFL_PARSER_ERROR_INVALID_METRIC,
	GTK_CONSTRAINT_VFL_PARSER_ERROR_INVALID_PRIORITY,
	GTK_CONSTRAINT_VFL_PARSER_ERROR_INVALID_RELATION
}

public enum GtkTextWindowType : uint
{
	GTK_TEXT_WINDOW_WIDGET = 1,
	GTK_TEXT_WINDOW_TEXT,
	GTK_TEXT_WINDOW_LEFT,
	GTK_TEXT_WINDOW_RIGHT,
	GTK_TEXT_WINDOW_TOP,
	GTK_TEXT_WINDOW_BOTTOM
}

public enum GtkRevealerTransitionType : uint
{
	GTK_REVEALER_TRANSITION_TYPE_NONE,
	GTK_REVEALER_TRANSITION_TYPE_CROSSFADE,
	GTK_REVEALER_TRANSITION_TYPE_SLIDE_RIGHT,
	GTK_REVEALER_TRANSITION_TYPE_SLIDE_LEFT,
	GTK_REVEALER_TRANSITION_TYPE_SLIDE_UP,
	GTK_REVEALER_TRANSITION_TYPE_SLIDE_DOWN,
	GTK_REVEALER_TRANSITION_TYPE_SWING_RIGHT,
	GTK_REVEALER_TRANSITION_TYPE_SWING_LEFT,
	GTK_REVEALER_TRANSITION_TYPE_SWING_UP,
	GTK_REVEALER_TRANSITION_TYPE_SWING_DOWN
}

public enum GtkBorderStyle : uint
{
	GTK_BORDER_STYLE_NONE,
	GTK_BORDER_STYLE_HIDDEN,
	GTK_BORDER_STYLE_SOLID,
	GTK_BORDER_STYLE_INSET,
	GTK_BORDER_STYLE_OUTSET,
	GTK_BORDER_STYLE_DOTTED,
	GTK_BORDER_STYLE_DASHED,
	GTK_BORDER_STYLE_DOUBLE,
	GTK_BORDER_STYLE_GROOVE,
	GTK_BORDER_STYLE_RIDGE
}

public enum GtkScrollablePolicy : uint
{
	GTK_SCROLL_MINIMUM = 0,
	GTK_SCROLL_NATURAL
}

public enum GtkConstraintRelation
{
	GTK_CONSTRAINT_RELATION_LE = -1,
	GTK_CONSTRAINT_RELATION_EQ = 0,
	GTK_CONSTRAINT_RELATION_GE = 1
}

public enum GtkDeleteType : uint
{
	GTK_DELETE_CHARS,
	GTK_DELETE_WORD_ENDS,
	GTK_DELETE_WORDS,
	GTK_DELETE_DISPLAY_LINES,
	GTK_DELETE_DISPLAY_LINE_ENDS,
	GTK_DELETE_PARAGRAPH_ENDS,
	GTK_DELETE_PARAGRAPHS,
	GTK_DELETE_WHITESPACE
}

public enum GtkSymbolicColor : uint
{
	GTK_SYMBOLIC_COLOR_FOREGROUND = 0,
	GTK_SYMBOLIC_COLOR_ERROR = 1,
	GTK_SYMBOLIC_COLOR_WARNING = 2,
	GTK_SYMBOLIC_COLOR_SUCCESS = 3
}

public enum GtkBuilderClosureFlags : uint
{
	GTK_BUILDER_CLOSURE_SWAPPED = 1 << 0
}

public enum GtkPropagationLimit : uint
{
	GTK_LIMIT_NONE,
	GTK_LIMIT_SAME_NATIVE
}

public enum GtkAccessibleProperty : uint
{
	GTK_ACCESSIBLE_PROPERTY_AUTOCOMPLETE,
	GTK_ACCESSIBLE_PROPERTY_DESCRIPTION,
	GTK_ACCESSIBLE_PROPERTY_HAS_POPUP,
	GTK_ACCESSIBLE_PROPERTY_KEY_SHORTCUTS,
	GTK_ACCESSIBLE_PROPERTY_LABEL,
	GTK_ACCESSIBLE_PROPERTY_LEVEL,
	GTK_ACCESSIBLE_PROPERTY_MODAL,
	GTK_ACCESSIBLE_PROPERTY_MULTI_LINE,
	GTK_ACCESSIBLE_PROPERTY_MULTI_SELECTABLE,
	GTK_ACCESSIBLE_PROPERTY_ORIENTATION,
	GTK_ACCESSIBLE_PROPERTY_PLACEHOLDER,
	GTK_ACCESSIBLE_PROPERTY_READ_ONLY,
	GTK_ACCESSIBLE_PROPERTY_REQUIRED,
	GTK_ACCESSIBLE_PROPERTY_ROLE_DESCRIPTION,
	GTK_ACCESSIBLE_PROPERTY_SORT,
	GTK_ACCESSIBLE_PROPERTY_VALUE_MAX,
	GTK_ACCESSIBLE_PROPERTY_VALUE_MIN,
	GTK_ACCESSIBLE_PROPERTY_VALUE_NOW,
	GTK_ACCESSIBLE_PROPERTY_VALUE_TEXT
}
