namespace MentorLake.Gtk4.Gsk4;

public enum GskGLUniformType
{
	GSK_GL_UNIFORM_TYPE_NONE,
	GSK_GL_UNIFORM_TYPE_FLOAT,
	GSK_GL_UNIFORM_TYPE_INT,
	GSK_GL_UNIFORM_TYPE_UINT,
	GSK_GL_UNIFORM_TYPE_BOOL,
	GSK_GL_UNIFORM_TYPE_VEC2,
	GSK_GL_UNIFORM_TYPE_VEC3,
	GSK_GL_UNIFORM_TYPE_VEC4
}
