namespace MentorLake.Gtk4.Gsk4;

[Flags]
public enum GskPathForeachFlags
{
	GSK_PATH_FOREACH_ALLOW_ONLY_LINES = 0,
	GSK_PATH_FOREACH_ALLOW_QUAD = 1,
	GSK_PATH_FOREACH_ALLOW_CUBIC = 2,
	GSK_PATH_FOREACH_ALLOW_CONIC = 4
}
