namespace MentorLake.Gtk4.Gsk4;

public enum GskTransformCategory
{
	GSK_TRANSFORM_CATEGORY_UNKNOWN,
	GSK_TRANSFORM_CATEGORY_ANY,
	GSK_TRANSFORM_CATEGORY_3D,
	GSK_TRANSFORM_CATEGORY_2D,
	GSK_TRANSFORM_CATEGORY_2D_AFFINE,
	GSK_TRANSFORM_CATEGORY_2D_TRANSLATE,
	GSK_TRANSFORM_CATEGORY_IDENTITY
}
