namespace MentorLake.Gtk4.GObject;

[Flags]
public enum GSignalFlags
{
	G_SIGNAL_RUN_FIRST = 0,
	G_SIGNAL_RUN_LAST = 1,
	G_SIGNAL_RUN_CLEANUP = 2,
	G_SIGNAL_NO_RECURSE = 4,
	G_SIGNAL_DETAILED = 8,
	G_SIGNAL_ACTION = 16,
	G_SIGNAL_NO_HOOKS = 32,
	G_SIGNAL_MUST_COLLECT = 64,
	G_SIGNAL_DEPRECATED = 128,
	G_SIGNAL_ACCUMULATOR_FIRST_RUN = 256
}
