namespace MentorLake.Gtk4.Pixbuf;

public enum GdkInterpType : uint
{
	GDK_INTERP_NEAREST,
	GDK_INTERP_TILES,
	GDK_INTERP_BILINEAR,
	GDK_INTERP_HYPER
}

public enum GdkPixbufRotation : uint
{
	GDK_PIXBUF_ROTATE_NONE = 0,
	GDK_PIXBUF_ROTATE_COUNTERCLOCKWISE = 90,
	GDK_PIXBUF_ROTATE_UPSIDEDOWN = 180,
	GDK_PIXBUF_ROTATE_CLOCKWISE = 270
}

public enum GdkPixbufAlphaMode : uint
{
	GDK_PIXBUF_ALPHA_BILEVEL,
	GDK_PIXBUF_ALPHA_FULL
}

public enum GdkColorspace : uint
{
	GDK_COLORSPACE_RGB
}

public enum GdkPixbufError : uint
{
	GDK_PIXBUF_ERROR_CORRUPT_IMAGE,
	GDK_PIXBUF_ERROR_INSUFFICIENT_MEMORY,
	GDK_PIXBUF_ERROR_BAD_OPTION,
	GDK_PIXBUF_ERROR_UNKNOWN_TYPE,
	GDK_PIXBUF_ERROR_UNSUPPORTED_OPERATION,
	GDK_PIXBUF_ERROR_FAILED,
	GDK_PIXBUF_ERROR_INCOMPLETE_ANIMATION
}
