namespace MentorLake.Gtk4.Pango;

public enum PangoRenderPart : uint
{
	PANGO_RENDER_PART_FOREGROUND,
	PANGO_RENDER_PART_BACKGROUND,
	PANGO_RENDER_PART_UNDERLINE,
	PANGO_RENDER_PART_STRIKETHROUGH,
	PANGO_RENDER_PART_OVERLINE
}

public enum PangoShowFlags : uint
{
	PANGO_SHOW_NONE = 0,
	PANGO_SHOW_SPACES = 1 << 0,
	PANGO_SHOW_LINE_BREAKS = 1 << 1,
	PANGO_SHOW_IGNORABLES = 1 << 2
}

public enum PangoBidiType : uint
{
	PANGO_BIDI_TYPE_L,
	PANGO_BIDI_TYPE_LRE,
	PANGO_BIDI_TYPE_LRO,
	PANGO_BIDI_TYPE_R,
	PANGO_BIDI_TYPE_AL,
	PANGO_BIDI_TYPE_RLE,
	PANGO_BIDI_TYPE_RLO,
	PANGO_BIDI_TYPE_PDF,
	PANGO_BIDI_TYPE_EN,
	PANGO_BIDI_TYPE_ES,
	PANGO_BIDI_TYPE_ET,
	PANGO_BIDI_TYPE_AN,
	PANGO_BIDI_TYPE_CS,
	PANGO_BIDI_TYPE_NSM,
	PANGO_BIDI_TYPE_BN,
	PANGO_BIDI_TYPE_B,
	PANGO_BIDI_TYPE_S,
	PANGO_BIDI_TYPE_WS,
	PANGO_BIDI_TYPE_ON,
	PANGO_BIDI_TYPE_LRI,
	PANGO_BIDI_TYPE_RLI,
	PANGO_BIDI_TYPE_FSI,
	PANGO_BIDI_TYPE_PDI
}

public enum PangoOverline : uint
{
	PANGO_OVERLINE_NONE,
	PANGO_OVERLINE_SINGLE
}

public enum PangoFontMask : uint
{
	PANGO_FONT_MASK_FAMILY = 1 << 0,
	PANGO_FONT_MASK_STYLE = 1 << 1,
	PANGO_FONT_MASK_VARIANT = 1 << 2,
	PANGO_FONT_MASK_WEIGHT = 1 << 3,
	PANGO_FONT_MASK_STRETCH = 1 << 4,
	PANGO_FONT_MASK_SIZE = 1 << 5,
	PANGO_FONT_MASK_GRAVITY = 1 << 6,
	PANGO_FONT_MASK_VARIATIONS = 1 << 7
}

public enum PangoLayoutDeserializeError : uint
{
	PANGO_LAYOUT_DESERIALIZE_INVALID,
	PANGO_LAYOUT_DESERIALIZE_INVALID_VALUE,
	PANGO_LAYOUT_DESERIALIZE_MISSING_VALUE
}

public enum PangoStretch : uint
{
	PANGO_STRETCH_ULTRA_CONDENSED,
	PANGO_STRETCH_EXTRA_CONDENSED,
	PANGO_STRETCH_CONDENSED,
	PANGO_STRETCH_SEMI_CONDENSED,
	PANGO_STRETCH_NORMAL,
	PANGO_STRETCH_SEMI_EXPANDED,
	PANGO_STRETCH_EXPANDED,
	PANGO_STRETCH_EXTRA_EXPANDED,
	PANGO_STRETCH_ULTRA_EXPANDED
}

public enum PangoBaselineShift : uint
{
	PANGO_BASELINE_SHIFT_NONE,
	PANGO_BASELINE_SHIFT_SUPERSCRIPT,
	PANGO_BASELINE_SHIFT_SUBSCRIPT
}

public enum PangoEllipsizeMode : uint
{
	PANGO_ELLIPSIZE_NONE,
	PANGO_ELLIPSIZE_START,
	PANGO_ELLIPSIZE_MIDDLE,
	PANGO_ELLIPSIZE_END
}

public enum PangoDirection : uint
{
	PANGO_DIRECTION_LTR,
	PANGO_DIRECTION_RTL,
	PANGO_DIRECTION_TTB_LTR,
	PANGO_DIRECTION_TTB_RTL,
	PANGO_DIRECTION_WEAK_LTR,
	PANGO_DIRECTION_WEAK_RTL,
	PANGO_DIRECTION_NEUTRAL
}

public enum PangoAlignment : uint
{
	PANGO_ALIGN_LEFT,
	PANGO_ALIGN_CENTER,
	PANGO_ALIGN_RIGHT
}

public enum PangoScript
{
	PANGO_SCRIPT_INVALID_CODE = -1,
	PANGO_SCRIPT_COMMON = 0,
	PANGO_SCRIPT_INHERITED,
	PANGO_SCRIPT_ARABIC,
	PANGO_SCRIPT_ARMENIAN,
	PANGO_SCRIPT_BENGALI,
	PANGO_SCRIPT_BOPOMOFO,
	PANGO_SCRIPT_CHEROKEE,
	PANGO_SCRIPT_COPTIC,
	PANGO_SCRIPT_CYRILLIC,
	PANGO_SCRIPT_DESERET,
	PANGO_SCRIPT_DEVANAGARI,
	PANGO_SCRIPT_ETHIOPIC,
	PANGO_SCRIPT_GEORGIAN,
	PANGO_SCRIPT_GOTHIC,
	PANGO_SCRIPT_GREEK,
	PANGO_SCRIPT_GUJARATI,
	PANGO_SCRIPT_GURMUKHI,
	PANGO_SCRIPT_HAN,
	PANGO_SCRIPT_HANGUL,
	PANGO_SCRIPT_HEBREW,
	PANGO_SCRIPT_HIRAGANA,
	PANGO_SCRIPT_KANNADA,
	PANGO_SCRIPT_KATAKANA,
	PANGO_SCRIPT_KHMER,
	PANGO_SCRIPT_LAO,
	PANGO_SCRIPT_LATIN,
	PANGO_SCRIPT_MALAYALAM,
	PANGO_SCRIPT_MONGOLIAN,
	PANGO_SCRIPT_MYANMAR,
	PANGO_SCRIPT_OGHAM,
	PANGO_SCRIPT_OLD_ITALIC,
	PANGO_SCRIPT_ORIYA,
	PANGO_SCRIPT_RUNIC,
	PANGO_SCRIPT_SINHALA,
	PANGO_SCRIPT_SYRIAC,
	PANGO_SCRIPT_TAMIL,
	PANGO_SCRIPT_TELUGU,
	PANGO_SCRIPT_THAANA,
	PANGO_SCRIPT_THAI,
	PANGO_SCRIPT_TIBETAN,
	PANGO_SCRIPT_CANADIAN_ABORIGINAL,
	PANGO_SCRIPT_YI,
	PANGO_SCRIPT_TAGALOG,
	PANGO_SCRIPT_HANUNOO,
	PANGO_SCRIPT_BUHID,
	PANGO_SCRIPT_TAGBANWA,
	PANGO_SCRIPT_BRAILLE,
	PANGO_SCRIPT_CYPRIOT,
	PANGO_SCRIPT_LIMBU,
	PANGO_SCRIPT_OSMANYA,
	PANGO_SCRIPT_SHAVIAN,
	PANGO_SCRIPT_LINEAR_B,
	PANGO_SCRIPT_TAI_LE,
	PANGO_SCRIPT_UGARITIC,
	PANGO_SCRIPT_NEW_TAI_LUE,
	PANGO_SCRIPT_BUGINESE,
	PANGO_SCRIPT_GLAGOLITIC,
	PANGO_SCRIPT_TIFINAGH,
	PANGO_SCRIPT_SYLOTI_NAGRI,
	PANGO_SCRIPT_OLD_PERSIAN,
	PANGO_SCRIPT_KHAROSHTHI,
	PANGO_SCRIPT_UNKNOWN,
	PANGO_SCRIPT_BALINESE,
	PANGO_SCRIPT_CUNEIFORM,
	PANGO_SCRIPT_PHOENICIAN,
	PANGO_SCRIPT_PHAGS_PA,
	PANGO_SCRIPT_NKO,
	PANGO_SCRIPT_KAYAH_LI,
	PANGO_SCRIPT_LEPCHA,
	PANGO_SCRIPT_REJANG,
	PANGO_SCRIPT_SUNDANESE,
	PANGO_SCRIPT_SAURASHTRA,
	PANGO_SCRIPT_CHAM,
	PANGO_SCRIPT_OL_CHIKI,
	PANGO_SCRIPT_VAI,
	PANGO_SCRIPT_CARIAN,
	PANGO_SCRIPT_LYCIAN,
	PANGO_SCRIPT_LYDIAN,
	PANGO_SCRIPT_BATAK,
	PANGO_SCRIPT_BRAHMI,
	PANGO_SCRIPT_MANDAIC,
	PANGO_SCRIPT_CHAKMA,
	PANGO_SCRIPT_MEROITIC_CURSIVE,
	PANGO_SCRIPT_MEROITIC_HIEROGLYPHS,
	PANGO_SCRIPT_MIAO,
	PANGO_SCRIPT_SHARADA,
	PANGO_SCRIPT_SORA_SOMPENG,
	PANGO_SCRIPT_TAKRI,
	PANGO_SCRIPT_BASSA_VAH,
	PANGO_SCRIPT_CAUCASIAN_ALBANIAN,
	PANGO_SCRIPT_DUPLOYAN,
	PANGO_SCRIPT_ELBASAN,
	PANGO_SCRIPT_GRANTHA,
	PANGO_SCRIPT_KHOJKI,
	PANGO_SCRIPT_KHUDAWADI,
	PANGO_SCRIPT_LINEAR_A,
	PANGO_SCRIPT_MAHAJANI,
	PANGO_SCRIPT_MANICHAEAN,
	PANGO_SCRIPT_MENDE_KIKAKUI,
	PANGO_SCRIPT_MODI,
	PANGO_SCRIPT_MRO,
	PANGO_SCRIPT_NABATAEAN,
	PANGO_SCRIPT_OLD_NORTH_ARABIAN,
	PANGO_SCRIPT_OLD_PERMIC,
	PANGO_SCRIPT_PAHAWH_HMONG,
	PANGO_SCRIPT_PALMYRENE,
	PANGO_SCRIPT_PAU_CIN_HAU,
	PANGO_SCRIPT_PSALTER_PAHLAVI,
	PANGO_SCRIPT_SIDDHAM,
	PANGO_SCRIPT_TIRHUTA,
	PANGO_SCRIPT_WARANG_CITI,
	PANGO_SCRIPT_AHOM,
	PANGO_SCRIPT_ANATOLIAN_HIEROGLYPHS,
	PANGO_SCRIPT_HATRAN,
	PANGO_SCRIPT_MULTANI,
	PANGO_SCRIPT_OLD_HUNGARIAN,
	PANGO_SCRIPT_SIGNWRITING
}

public enum PangoStyle : uint
{
	PANGO_STYLE_NORMAL,
	PANGO_STYLE_OBLIQUE,
	PANGO_STYLE_ITALIC
}

public enum PangoWeight : uint
{
	PANGO_WEIGHT_THIN = 100,
	PANGO_WEIGHT_ULTRALIGHT = 200,
	PANGO_WEIGHT_LIGHT = 300,
	PANGO_WEIGHT_SEMILIGHT = 350,
	PANGO_WEIGHT_BOOK = 380,
	PANGO_WEIGHT_NORMAL = 400,
	PANGO_WEIGHT_MEDIUM = 500,
	PANGO_WEIGHT_SEMIBOLD = 600,
	PANGO_WEIGHT_BOLD = 700,
	PANGO_WEIGHT_ULTRABOLD = 800,
	PANGO_WEIGHT_HEAVY = 900,
	PANGO_WEIGHT_ULTRAHEAVY = 1000
}

public enum PangoUnderline : uint
{
	PANGO_UNDERLINE_NONE,
	PANGO_UNDERLINE_SINGLE,
	PANGO_UNDERLINE_DOUBLE,
	PANGO_UNDERLINE_LOW,
	PANGO_UNDERLINE_ERROR,
	PANGO_UNDERLINE_SINGLE_LINE,
	PANGO_UNDERLINE_DOUBLE_LINE,
	PANGO_UNDERLINE_ERROR_LINE
}

public enum PangoCoverageLevel : uint
{
	PANGO_COVERAGE_NONE,
	PANGO_COVERAGE_FALLBACK,
	PANGO_COVERAGE_APPROXIMATE,
	PANGO_COVERAGE_EXACT
}

public enum PangoWrapMode : uint
{
	PANGO_WRAP_WORD,
	PANGO_WRAP_CHAR,
	PANGO_WRAP_WORD_CHAR
}

public enum PangoLayoutDeserializeFlags : uint
{
	PANGO_LAYOUT_DESERIALIZE_DEFAULT = 0,
	PANGO_LAYOUT_DESERIALIZE_CONTEXT = 1 << 0
}

public enum PangoVariant : uint
{
	PANGO_VARIANT_NORMAL,
	PANGO_VARIANT_SMALL_CAPS,
	PANGO_VARIANT_ALL_SMALL_CAPS,
	PANGO_VARIANT_PETITE_CAPS,
	PANGO_VARIANT_ALL_PETITE_CAPS,
	PANGO_VARIANT_UNICASE,
	PANGO_VARIANT_TITLE_CAPS
}

public enum PangoTextTransform : uint
{
	PANGO_TEXT_TRANSFORM_NONE,
	PANGO_TEXT_TRANSFORM_LOWERCASE,
	PANGO_TEXT_TRANSFORM_UPPERCASE,
	PANGO_TEXT_TRANSFORM_CAPITALIZE
}

public enum PangoFontScale : uint
{
	PANGO_FONT_SCALE_NONE,
	PANGO_FONT_SCALE_SUPERSCRIPT,
	PANGO_FONT_SCALE_SUBSCRIPT,
	PANGO_FONT_SCALE_SMALL_CAPS
}

public enum PangoLayoutSerializeFlags : uint
{
	PANGO_LAYOUT_SERIALIZE_DEFAULT = 0,
	PANGO_LAYOUT_SERIALIZE_CONTEXT = 1 << 0,
	PANGO_LAYOUT_SERIALIZE_OUTPUT = 1 << 1
}

public enum PangoShapeFlags : uint
{
	PANGO_SHAPE_NONE = 0,
	PANGO_SHAPE_ROUND_POSITIONS = 1 << 0
}

public enum PangoGravity : uint
{
	PANGO_GRAVITY_SOUTH,
	PANGO_GRAVITY_EAST,
	PANGO_GRAVITY_NORTH,
	PANGO_GRAVITY_WEST,
	PANGO_GRAVITY_AUTO
}

public enum PangoGravityHint : uint
{
	PANGO_GRAVITY_HINT_NATURAL,
	PANGO_GRAVITY_HINT_STRONG,
	PANGO_GRAVITY_HINT_LINE
}

public enum PangoTabAlign : uint
{
	PANGO_TAB_LEFT,
	PANGO_TAB_RIGHT,
	PANGO_TAB_CENTER,
	PANGO_TAB_DECIMAL
}

public enum PangoAttrType : uint
{
	PANGO_ATTR_INVALID,
	PANGO_ATTR_LANGUAGE,
	PANGO_ATTR_FAMILY,
	PANGO_ATTR_STYLE,
	PANGO_ATTR_WEIGHT,
	PANGO_ATTR_VARIANT,
	PANGO_ATTR_STRETCH,
	PANGO_ATTR_SIZE,
	PANGO_ATTR_FONT_DESC,
	PANGO_ATTR_FOREGROUND,
	PANGO_ATTR_BACKGROUND,
	PANGO_ATTR_UNDERLINE,
	PANGO_ATTR_STRIKETHROUGH,
	PANGO_ATTR_RISE,
	PANGO_ATTR_SHAPE,
	PANGO_ATTR_SCALE,
	PANGO_ATTR_FALLBACK,
	PANGO_ATTR_LETTER_SPACING,
	PANGO_ATTR_UNDERLINE_COLOR,
	PANGO_ATTR_STRIKETHROUGH_COLOR,
	PANGO_ATTR_ABSOLUTE_SIZE,
	PANGO_ATTR_GRAVITY,
	PANGO_ATTR_GRAVITY_HINT,
	PANGO_ATTR_FONT_FEATURES,
	PANGO_ATTR_FOREGROUND_ALPHA,
	PANGO_ATTR_BACKGROUND_ALPHA,
	PANGO_ATTR_ALLOW_BREAKS,
	PANGO_ATTR_SHOW,
	PANGO_ATTR_INSERT_HYPHENS,
	PANGO_ATTR_OVERLINE,
	PANGO_ATTR_OVERLINE_COLOR,
	PANGO_ATTR_LINE_HEIGHT,
	PANGO_ATTR_ABSOLUTE_LINE_HEIGHT,
	PANGO_ATTR_TEXT_TRANSFORM,
	PANGO_ATTR_WORD,
	PANGO_ATTR_SENTENCE,
	PANGO_ATTR_BASELINE_SHIFT,
	PANGO_ATTR_FONT_SCALE
}
