namespace MentorLake.Gtk4.Pango;

public enum PangoDirection
{
	PANGO_DIRECTION_LTR,
	PANGO_DIRECTION_RTL,
	PANGO_DIRECTION_TTB_LTR,
	PANGO_DIRECTION_TTB_RTL,
	PANGO_DIRECTION_WEAK_LTR,
	PANGO_DIRECTION_WEAK_RTL,
	PANGO_DIRECTION_NEUTRAL
}
