namespace MentorLake.Gtk4.Pango;

[Flags]
public enum PangoFontMask
{
	PANGO_FONT_MASK_FAMILY = 0,
	PANGO_FONT_MASK_STYLE = 1,
	PANGO_FONT_MASK_VARIANT = 2,
	PANGO_FONT_MASK_WEIGHT = 4,
	PANGO_FONT_MASK_STRETCH = 8,
	PANGO_FONT_MASK_SIZE = 16,
	PANGO_FONT_MASK_GRAVITY = 32,
	PANGO_FONT_MASK_VARIATIONS = 64
}
