namespace MentorLake.Gtk4.Pango;

public enum PangoUnderline
{
	PANGO_UNDERLINE_NONE,
	PANGO_UNDERLINE_SINGLE,
	PANGO_UNDERLINE_DOUBLE,
	PANGO_UNDERLINE_LOW,
	PANGO_UNDERLINE_ERROR,
	PANGO_UNDERLINE_SINGLE_LINE,
	PANGO_UNDERLINE_DOUBLE_LINE,
	PANGO_UNDERLINE_ERROR_LINE
}
