namespace MentorLake.Gtk4.Pango;

public enum PangoRenderPart
{
	PANGO_RENDER_PART_FOREGROUND,
	PANGO_RENDER_PART_BACKGROUND,
	PANGO_RENDER_PART_UNDERLINE,
	PANGO_RENDER_PART_STRIKETHROUGH,
	PANGO_RENDER_PART_OVERLINE
}
