namespace MentorLake.Gtk4.Pango;

public enum PangoWeight
{
	PANGO_WEIGHT_THIN,
	PANGO_WEIGHT_ULTRALIGHT,
	PANGO_WEIGHT_LIGHT,
	PANGO_WEIGHT_SEMILIGHT,
	PANGO_WEIGHT_BOOK,
	PANGO_WEIGHT_NORMAL,
	PANGO_WEIGHT_MEDIUM,
	PANGO_WEIGHT_SEMIBOLD,
	PANGO_WEIGHT_BOLD,
	PANGO_WEIGHT_ULTRABOLD,
	PANGO_WEIGHT_HEAVY,
	PANGO_WEIGHT_ULTRAHEAVY
}
