namespace MentorLake.Gtk4.Pango;

public enum PangoVariant
{
	PANGO_VARIANT_NORMAL,
	PANGO_VARIANT_SMALL_CAPS,
	PANGO_VARIANT_ALL_SMALL_CAPS,
	PANGO_VARIANT_PETITE_CAPS,
	PANGO_VARIANT_ALL_PETITE_CAPS,
	PANGO_VARIANT_UNICASE,
	PANGO_VARIANT_TITLE_CAPS
}
