namespace MentorLake.Gtk4.Gtk4;

public enum GtkAccessibleInvalidState
{
	GTK_ACCESSIBLE_INVALID_FALSE,
	GTK_ACCESSIBLE_INVALID_TRUE,
	GTK_ACCESSIBLE_INVALID_GRAMMAR,
	GTK_ACCESSIBLE_INVALID_SPELLING
}
