namespace MentorLake.Gtk4.Gtk4;

public enum GtkAccessibleState
{
	GTK_ACCESSIBLE_STATE_BUSY,
	GTK_ACCESSIBLE_STATE_CHECKED,
	GTK_ACCESSIBLE_STATE_DISABLED,
	GTK_ACCESSIBLE_STATE_EXPANDED,
	GTK_ACCESSIBLE_STATE_HIDDEN,
	GTK_ACCESSIBLE_STATE_INVALID,
	GTK_ACCESSIBLE_STATE_PRESSED,
	GTK_ACCESSIBLE_STATE_SELECTED,
	GTK_ACCESSIBLE_STATE_VISITED
}
