namespace MentorLake.Gtk4.Gtk4;

public enum GtkAlign
{
	GTK_ALIGN_FILL,
	GTK_ALIGN_START,
	GTK_ALIGN_END,
	GTK_ALIGN_CENTER,
	GTK_ALIGN_BASELINE_FILL,
	GTK_ALIGN_BASELINE,
	GTK_ALIGN_BASELINE_CENTER
}
