using MentorLake.Gtk4.Graphene;
using MentorLake.Gtk4.Cairo;
using MentorLake.Gtk4.Harfbuzz;
using System.Runtime.InteropServices;
using System.Reactive;
using System.Reactive.Disposables;
using System.Reactive.Linq;using MentorLake.Gtk4.GLib;
using MentorLake.Gtk4.GObject;
using MentorLake.Gtk4.Gio;
using MentorLake.Gtk4.GModule;
using MentorLake.Gtk4.Pango;
using MentorLake.Gtk4.GdkPixbuf;
using MentorLake.Gtk4.Gdk4;
using MentorLake.Gtk4.Gsk4;
using MentorLake.Gtk4.Gtk4;

namespace MentorLake.Gtk4.Gtk4;

public enum GtkAccessibleProperty
{
	GTK_ACCESSIBLE_PROPERTY_AUTOCOMPLETE,
	GTK_ACCESSIBLE_PROPERTY_DESCRIPTION,
	GTK_ACCESSIBLE_PROPERTY_HAS_POPUP,
	GTK_ACCESSIBLE_PROPERTY_KEY_SHORTCUTS,
	GTK_ACCESSIBLE_PROPERTY_LABEL,
	GTK_ACCESSIBLE_PROPERTY_LEVEL,
	GTK_ACCESSIBLE_PROPERTY_MODAL,
	GTK_ACCESSIBLE_PROPERTY_MULTI_LINE,
	GTK_ACCESSIBLE_PROPERTY_MULTI_SELECTABLE,
	GTK_ACCESSIBLE_PROPERTY_ORIENTATION,
	GTK_ACCESSIBLE_PROPERTY_PLACEHOLDER,
	GTK_ACCESSIBLE_PROPERTY_READ_ONLY,
	GTK_ACCESSIBLE_PROPERTY_REQUIRED,
	GTK_ACCESSIBLE_PROPERTY_ROLE_DESCRIPTION,
	GTK_ACCESSIBLE_PROPERTY_SORT,
	GTK_ACCESSIBLE_PROPERTY_VALUE_MAX,
	GTK_ACCESSIBLE_PROPERTY_VALUE_MIN,
	GTK_ACCESSIBLE_PROPERTY_VALUE_NOW,
	GTK_ACCESSIBLE_PROPERTY_VALUE_TEXT
}
