using MentorLake.Gtk4.Graphene;
using MentorLake.Gtk4.Cairo;
using MentorLake.Gtk4.Harfbuzz;
using System.Runtime.InteropServices;
using MentorLake.Gtk4.GLib;
using MentorLake.Gtk4.GObject;
using MentorLake.Gtk4.Gio;
using MentorLake.Gtk4.GModule;
using MentorLake.Gtk4.Pango;
using MentorLake.Gtk4.GdkPixbuf;
using MentorLake.Gtk4.Gdk4;
using MentorLake.Gtk4.Gsk4;
using MentorLake.Gtk4.Gtk4;

namespace MentorLake.Gtk4.Gtk4;

public enum GtkAccessibleRole
{
	GTK_ACCESSIBLE_ROLE_ALERT,
	GTK_ACCESSIBLE_ROLE_ALERT_DIALOG,
	GTK_ACCESSIBLE_ROLE_BANNER,
	GTK_ACCESSIBLE_ROLE_BUTTON,
	GTK_ACCESSIBLE_ROLE_CAPTION,
	GTK_ACCESSIBLE_ROLE_CELL,
	GTK_ACCESSIBLE_ROLE_CHECKBOX,
	GTK_ACCESSIBLE_ROLE_COLUMN_HEADER,
	GTK_ACCESSIBLE_ROLE_COMBO_BOX,
	GTK_ACCESSIBLE_ROLE_COMMAND,
	GTK_ACCESSIBLE_ROLE_COMPOSITE,
	GTK_ACCESSIBLE_ROLE_DIALOG,
	GTK_ACCESSIBLE_ROLE_DOCUMENT,
	GTK_ACCESSIBLE_ROLE_FEED,
	GTK_ACCESSIBLE_ROLE_FORM,
	GTK_ACCESSIBLE_ROLE_GENERIC,
	GTK_ACCESSIBLE_ROLE_GRID,
	GTK_ACCESSIBLE_ROLE_GRID_CELL,
	GTK_ACCESSIBLE_ROLE_GROUP,
	GTK_ACCESSIBLE_ROLE_HEADING,
	GTK_ACCESSIBLE_ROLE_IMG,
	GTK_ACCESSIBLE_ROLE_INPUT,
	GTK_ACCESSIBLE_ROLE_LABEL,
	GTK_ACCESSIBLE_ROLE_LANDMARK,
	GTK_ACCESSIBLE_ROLE_LEGEND,
	GTK_ACCESSIBLE_ROLE_LINK,
	GTK_ACCESSIBLE_ROLE_LIST,
	GTK_ACCESSIBLE_ROLE_LIST_BOX,
	GTK_ACCESSIBLE_ROLE_LIST_ITEM,
	GTK_ACCESSIBLE_ROLE_LOG,
	GTK_ACCESSIBLE_ROLE_MAIN,
	GTK_ACCESSIBLE_ROLE_MARQUEE,
	GTK_ACCESSIBLE_ROLE_MATH,
	GTK_ACCESSIBLE_ROLE_METER,
	GTK_ACCESSIBLE_ROLE_MENU,
	GTK_ACCESSIBLE_ROLE_MENU_BAR,
	GTK_ACCESSIBLE_ROLE_MENU_ITEM,
	GTK_ACCESSIBLE_ROLE_MENU_ITEM_CHECKBOX,
	GTK_ACCESSIBLE_ROLE_MENU_ITEM_RADIO,
	GTK_ACCESSIBLE_ROLE_NAVIGATION,
	GTK_ACCESSIBLE_ROLE_NONE,
	GTK_ACCESSIBLE_ROLE_NOTE,
	GTK_ACCESSIBLE_ROLE_OPTION,
	GTK_ACCESSIBLE_ROLE_PRESENTATION,
	GTK_ACCESSIBLE_ROLE_PROGRESS_BAR,
	GTK_ACCESSIBLE_ROLE_RADIO,
	GTK_ACCESSIBLE_ROLE_RADIO_GROUP,
	GTK_ACCESSIBLE_ROLE_RANGE,
	GTK_ACCESSIBLE_ROLE_REGION,
	GTK_ACCESSIBLE_ROLE_ROW,
	GTK_ACCESSIBLE_ROLE_ROW_GROUP,
	GTK_ACCESSIBLE_ROLE_ROW_HEADER,
	GTK_ACCESSIBLE_ROLE_SCROLLBAR,
	GTK_ACCESSIBLE_ROLE_SEARCH,
	GTK_ACCESSIBLE_ROLE_SEARCH_BOX,
	GTK_ACCESSIBLE_ROLE_SECTION,
	GTK_ACCESSIBLE_ROLE_SECTION_HEAD,
	GTK_ACCESSIBLE_ROLE_SELECT,
	GTK_ACCESSIBLE_ROLE_SEPARATOR,
	GTK_ACCESSIBLE_ROLE_SLIDER,
	GTK_ACCESSIBLE_ROLE_SPIN_BUTTON,
	GTK_ACCESSIBLE_ROLE_STATUS,
	GTK_ACCESSIBLE_ROLE_STRUCTURE,
	GTK_ACCESSIBLE_ROLE_SWITCH,
	GTK_ACCESSIBLE_ROLE_TAB,
	GTK_ACCESSIBLE_ROLE_TABLE,
	GTK_ACCESSIBLE_ROLE_TAB_LIST,
	GTK_ACCESSIBLE_ROLE_TAB_PANEL,
	GTK_ACCESSIBLE_ROLE_TEXT_BOX,
	GTK_ACCESSIBLE_ROLE_TIME,
	GTK_ACCESSIBLE_ROLE_TIMER,
	GTK_ACCESSIBLE_ROLE_TOOLBAR,
	GTK_ACCESSIBLE_ROLE_TOOLTIP,
	GTK_ACCESSIBLE_ROLE_TREE,
	GTK_ACCESSIBLE_ROLE_TREE_GRID,
	GTK_ACCESSIBLE_ROLE_TREE_ITEM,
	GTK_ACCESSIBLE_ROLE_WIDGET,
	GTK_ACCESSIBLE_ROLE_WINDOW,
	GTK_ACCESSIBLE_ROLE_TOGGLE_BUTTON,
	GTK_ACCESSIBLE_ROLE_APPLICATION,
	GTK_ACCESSIBLE_ROLE_PARAGRAPH,
	GTK_ACCESSIBLE_ROLE_BLOCK_QUOTE,
	GTK_ACCESSIBLE_ROLE_ARTICLE,
	GTK_ACCESSIBLE_ROLE_COMMENT,
	GTK_ACCESSIBLE_ROLE_TERMINAL
}
