namespace MentorLake.Gtk4.Gtk4;

public enum GtkAccessibleAutocomplete
{
	GTK_ACCESSIBLE_AUTOCOMPLETE_NONE,
	GTK_ACCESSIBLE_AUTOCOMPLETE_INLINE,
	GTK_ACCESSIBLE_AUTOCOMPLETE_LIST,
	GTK_ACCESSIBLE_AUTOCOMPLETE_BOTH
}
