namespace MentorLake.Gtk4.Gtk4;

public enum GtkBorderStyle
{
	GTK_BORDER_STYLE_NONE,
	GTK_BORDER_STYLE_HIDDEN,
	GTK_BORDER_STYLE_SOLID,
	GTK_BORDER_STYLE_INSET,
	GTK_BORDER_STYLE_OUTSET,
	GTK_BORDER_STYLE_DOTTED,
	GTK_BORDER_STYLE_DASHED,
	GTK_BORDER_STYLE_DOUBLE,
	GTK_BORDER_STYLE_GROOVE,
	GTK_BORDER_STYLE_RIDGE
}
