namespace MentorLake.Gtk4.Gtk4;

[Flags]
public enum GtkCellRendererState
{
	GTK_CELL_RENDERER_SELECTED = 0,
	GTK_CELL_RENDERER_PRELIT = 1,
	GTK_CELL_RENDERER_INSENSITIVE = 2,
	GTK_CELL_RENDERER_SORTED = 4,
	GTK_CELL_RENDERER_FOCUSED = 8,
	GTK_CELL_RENDERER_EXPANDABLE = 16,
	GTK_CELL_RENDERER_EXPANDED = 32
}
