namespace MentorLake.Gtk4.Gtk4;

public enum GtkConstraintStrength
{
	GTK_CONSTRAINT_STRENGTH_REQUIRED,
	GTK_CONSTRAINT_STRENGTH_STRONG,
	GTK_CONSTRAINT_STRENGTH_MEDIUM,
	GTK_CONSTRAINT_STRENGTH_WEAK
}
