namespace MentorLake.Gtk4.Gtk4;

public enum GtkCssParserError
{
	GTK_CSS_PARSER_ERROR_FAILED,
	GTK_CSS_PARSER_ERROR_SYNTAX,
	GTK_CSS_PARSER_ERROR_IMPORT,
	GTK_CSS_PARSER_ERROR_NAME,
	GTK_CSS_PARSER_ERROR_UNKNOWN_VALUE
}
