namespace MentorLake.Gtk4.Gtk4;

public enum GtkConstraintAttribute
{
	GTK_CONSTRAINT_ATTRIBUTE_NONE,
	GTK_CONSTRAINT_ATTRIBUTE_LEFT,
	GTK_CONSTRAINT_ATTRIBUTE_RIGHT,
	GTK_CONSTRAINT_ATTRIBUTE_TOP,
	GTK_CONSTRAINT_ATTRIBUTE_BOTTOM,
	GTK_CONSTRAINT_ATTRIBUTE_START,
	GTK_CONSTRAINT_ATTRIBUTE_END,
	GTK_CONSTRAINT_ATTRIBUTE_WIDTH,
	GTK_CONSTRAINT_ATTRIBUTE_HEIGHT,
	GTK_CONSTRAINT_ATTRIBUTE_CENTER_X,
	GTK_CONSTRAINT_ATTRIBUTE_CENTER_Y,
	GTK_CONSTRAINT_ATTRIBUTE_BASELINE
}
