namespace MentorLake.Gtk4.Gtk4;

public enum GtkDeleteType
{
	GTK_DELETE_CHARS,
	GTK_DELETE_WORD_ENDS,
	GTK_DELETE_WORDS,
	GTK_DELETE_DISPLAY_LINES,
	GTK_DELETE_DISPLAY_LINE_ENDS,
	GTK_DELETE_PARAGRAPH_ENDS,
	GTK_DELETE_PARAGRAPHS,
	GTK_DELETE_WHITESPACE
}
