namespace MentorLake.Gtk4.Gtk4;

public enum GtkEditableProperties
{
	GTK_EDITABLE_PROP_TEXT,
	GTK_EDITABLE_PROP_CURSOR_POSITION,
	GTK_EDITABLE_PROP_SELECTION_BOUND,
	GTK_EDITABLE_PROP_EDITABLE,
	GTK_EDITABLE_PROP_WIDTH_CHARS,
	GTK_EDITABLE_PROP_MAX_WIDTH_CHARS,
	GTK_EDITABLE_PROP_XALIGN,
	GTK_EDITABLE_PROP_ENABLE_UNDO,
	GTK_EDITABLE_NUM_PROPERTIES
}
