namespace MentorLake.Gtk4.Gtk4;

public enum GtkInscriptionOverflow
{
	GTK_INSCRIPTION_OVERFLOW_CLIP,
	GTK_INSCRIPTION_OVERFLOW_ELLIPSIZE_START,
	GTK_INSCRIPTION_OVERFLOW_ELLIPSIZE_MIDDLE,
	GTK_INSCRIPTION_OVERFLOW_ELLIPSIZE_END
}
