namespace MentorLake.Gtk4.Gtk4;

public enum GtkInputPurpose
{
	GTK_INPUT_PURPOSE_FREE_FORM,
	GTK_INPUT_PURPOSE_ALPHA,
	GTK_INPUT_PURPOSE_DIGITS,
	GTK_INPUT_PURPOSE_NUMBER,
	GTK_INPUT_PURPOSE_PHONE,
	GTK_INPUT_PURPOSE_URL,
	GTK_INPUT_PURPOSE_EMAIL,
	GTK_INPUT_PURPOSE_NAME,
	GTK_INPUT_PURPOSE_PASSWORD,
	GTK_INPUT_PURPOSE_PIN,
	GTK_INPUT_PURPOSE_TERMINAL
}
