namespace MentorLake.Gtk4.Gtk4;

public enum GtkIconViewDropPosition
{
	GTK_ICON_VIEW_NO_DROP,
	GTK_ICON_VIEW_DROP_INTO,
	GTK_ICON_VIEW_DROP_LEFT,
	GTK_ICON_VIEW_DROP_RIGHT,
	GTK_ICON_VIEW_DROP_ABOVE,
	GTK_ICON_VIEW_DROP_BELOW
}
