namespace MentorLake.Gtk4.Gtk4;

public enum GtkLicense
{
	GTK_LICENSE_UNKNOWN,
	GTK_LICENSE_CUSTOM,
	GTK_LICENSE_GPL_2_0,
	GTK_LICENSE_GPL_3_0,
	GTK_LICENSE_LGPL_2_1,
	GTK_LICENSE_LGPL_3_0,
	GTK_LICENSE_BSD,
	GTK_LICENSE_MIT_X11,
	GTK_LICENSE_ARTISTIC,
	GTK_LICENSE_GPL_2_0_ONLY,
	GTK_LICENSE_GPL_3_0_ONLY,
	GTK_LICENSE_LGPL_2_1_ONLY,
	GTK_LICENSE_LGPL_3_0_ONLY,
	GTK_LICENSE_AGPL_3_0,
	GTK_LICENSE_AGPL_3_0_ONLY,
	GTK_LICENSE_BSD_3,
	GTK_LICENSE_APACHE_2_0,
	GTK_LICENSE_MPL_2_0,
	GTK_LICENSE_0BSD
}
