namespace MentorLake.Gtk4.Gtk4;

public enum GtkMovementStep
{
	GTK_MOVEMENT_LOGICAL_POSITIONS,
	GTK_MOVEMENT_VISUAL_POSITIONS,
	GTK_MOVEMENT_WORDS,
	GTK_MOVEMENT_DISPLAY_LINES,
	GTK_MOVEMENT_DISPLAY_LINE_ENDS,
	GTK_MOVEMENT_PARAGRAPHS,
	GTK_MOVEMENT_PARAGRAPH_ENDS,
	GTK_MOVEMENT_PAGES,
	GTK_MOVEMENT_BUFFER_ENDS,
	GTK_MOVEMENT_HORIZONTAL_PAGES
}
