namespace MentorLake.Gtk4.Gtk4;

public enum GtkPrintOperationResult
{
	GTK_PRINT_OPERATION_RESULT_ERROR,
	GTK_PRINT_OPERATION_RESULT_APPLY,
	GTK_PRINT_OPERATION_RESULT_CANCEL,
	GTK_PRINT_OPERATION_RESULT_IN_PROGRESS
}
