namespace MentorLake.Gtk4.Gtk4;

public enum GtkPageOrientation
{
	GTK_PAGE_ORIENTATION_PORTRAIT,
	GTK_PAGE_ORIENTATION_LANDSCAPE,
	GTK_PAGE_ORIENTATION_REVERSE_PORTRAIT,
	GTK_PAGE_ORIENTATION_REVERSE_LANDSCAPE
}
