namespace MentorLake.Gtk4.Gtk4;

public enum GtkPrintStatus
{
	GTK_PRINT_STATUS_INITIAL,
	GTK_PRINT_STATUS_PREPARING,
	GTK_PRINT_STATUS_GENERATING_DATA,
	GTK_PRINT_STATUS_SENDING_DATA,
	GTK_PRINT_STATUS_PENDING,
	GTK_PRINT_STATUS_PENDING_ISSUE,
	GTK_PRINT_STATUS_PRINTING,
	GTK_PRINT_STATUS_FINISHED,
	GTK_PRINT_STATUS_FINISHED_ABORTED
}
