namespace MentorLake.Gtk4.Gtk4;

public enum GtkResponseType
{
	GTK_RESPONSE_NONE,
	GTK_RESPONSE_REJECT,
	GTK_RESPONSE_ACCEPT,
	GTK_RESPONSE_DELETE_EVENT,
	GTK_RESPONSE_OK,
	GTK_RESPONSE_CANCEL,
	GTK_RESPONSE_CLOSE,
	GTK_RESPONSE_YES,
	GTK_RESPONSE_NO,
	GTK_RESPONSE_APPLY,
	GTK_RESPONSE_HELP
}
