using MentorLake.Gtk4.Graphene;
using MentorLake.Gtk4.Cairo;
using MentorLake.Gtk4.Harfbuzz;
using System.Runtime.InteropServices;
using MentorLake.Gtk4.GLib;
using MentorLake.Gtk4.GObject;
using MentorLake.Gtk4.Gio;
using MentorLake.Gtk4.GModule;
using MentorLake.Gtk4.Pango;
using MentorLake.Gtk4.GdkPixbuf;
using MentorLake.Gtk4.Gdk4;
using MentorLake.Gtk4.Gsk4;
using MentorLake.Gtk4.Gtk4;

namespace MentorLake.Gtk4.Gtk4;

public enum GtkStackTransitionType
{
	GTK_STACK_TRANSITION_TYPE_NONE,
	GTK_STACK_TRANSITION_TYPE_CROSSFADE,
	GTK_STACK_TRANSITION_TYPE_SLIDE_RIGHT,
	GTK_STACK_TRANSITION_TYPE_SLIDE_LEFT,
	GTK_STACK_TRANSITION_TYPE_SLIDE_UP,
	GTK_STACK_TRANSITION_TYPE_SLIDE_DOWN,
	GTK_STACK_TRANSITION_TYPE_SLIDE_LEFT_RIGHT,
	GTK_STACK_TRANSITION_TYPE_SLIDE_UP_DOWN,
	GTK_STACK_TRANSITION_TYPE_OVER_UP,
	GTK_STACK_TRANSITION_TYPE_OVER_DOWN,
	GTK_STACK_TRANSITION_TYPE_OVER_LEFT,
	GTK_STACK_TRANSITION_TYPE_OVER_RIGHT,
	GTK_STACK_TRANSITION_TYPE_UNDER_UP,
	GTK_STACK_TRANSITION_TYPE_UNDER_DOWN,
	GTK_STACK_TRANSITION_TYPE_UNDER_LEFT,
	GTK_STACK_TRANSITION_TYPE_UNDER_RIGHT,
	GTK_STACK_TRANSITION_TYPE_OVER_UP_DOWN,
	GTK_STACK_TRANSITION_TYPE_OVER_DOWN_UP,
	GTK_STACK_TRANSITION_TYPE_OVER_LEFT_RIGHT,
	GTK_STACK_TRANSITION_TYPE_OVER_RIGHT_LEFT,
	GTK_STACK_TRANSITION_TYPE_ROTATE_LEFT,
	GTK_STACK_TRANSITION_TYPE_ROTATE_RIGHT,
	GTK_STACK_TRANSITION_TYPE_ROTATE_LEFT_RIGHT
}
