namespace MentorLake.Gtk4.Gtk4;

public enum GtkScrollStep
{
	GTK_SCROLL_STEPS,
	GTK_SCROLL_PAGES,
	GTK_SCROLL_ENDS,
	GTK_SCROLL_HORIZONTAL_STEPS,
	GTK_SCROLL_HORIZONTAL_PAGES,
	GTK_SCROLL_HORIZONTAL_ENDS
}
