namespace MentorLake.Gtk4.Gtk4;

public enum GtkSystemSetting
{
	GTK_SYSTEM_SETTING_DPI,
	GTK_SYSTEM_SETTING_FONT_NAME,
	GTK_SYSTEM_SETTING_FONT_CONFIG,
	GTK_SYSTEM_SETTING_DISPLAY,
	GTK_SYSTEM_SETTING_ICON_THEME
}
