namespace MentorLake.Gtk4.Gtk4;

[Flags]
public enum GtkStyleContextPrintFlags
{
	GTK_STYLE_CONTEXT_PRINT_NONE = 0,
	GTK_STYLE_CONTEXT_PRINT_RECURSE = 1,
	GTK_STYLE_CONTEXT_PRINT_SHOW_STYLE = 2,
	GTK_STYLE_CONTEXT_PRINT_SHOW_CHANGE = 4
}
