namespace MentorLake.Gtk4.Gtk4;

public enum GtkTreeViewGridLines
{
	GTK_TREE_VIEW_GRID_LINES_NONE,
	GTK_TREE_VIEW_GRID_LINES_HORIZONTAL,
	GTK_TREE_VIEW_GRID_LINES_VERTICAL,
	GTK_TREE_VIEW_GRID_LINES_BOTH
}
