namespace MentorLake.Gtk4.Gtk4;

public enum GtkTextWindowType
{
	GTK_TEXT_WINDOW_WIDGET,
	GTK_TEXT_WINDOW_TEXT,
	GTK_TEXT_WINDOW_LEFT,
	GTK_TEXT_WINDOW_RIGHT,
	GTK_TEXT_WINDOW_TOP,
	GTK_TEXT_WINDOW_BOTTOM
}
