namespace MentorLake.Gtk4.GLib;

public enum GDateWeekday
{
	G_DATE_BAD_WEEKDAY,
	G_DATE_MONDAY,
	G_DATE_TUESDAY,
	G_DATE_WEDNESDAY,
	G_DATE_THURSDAY,
	G_DATE_FRIDAY,
	G_DATE_SATURDAY,
	G_DATE_SUNDAY
}
