namespace MentorLake.Gtk4.GLib;

public enum GDateMonth
{
	G_DATE_BAD_MONTH,
	G_DATE_JANUARY,
	G_DATE_FEBRUARY,
	G_DATE_MARCH,
	G_DATE_APRIL,
	G_DATE_MAY,
	G_DATE_JUNE,
	G_DATE_JULY,
	G_DATE_AUGUST,
	G_DATE_SEPTEMBER,
	G_DATE_OCTOBER,
	G_DATE_NOVEMBER,
	G_DATE_DECEMBER
}
