namespace MentorLake.Gtk4.GLib;

[Flags]
public enum GFormatSizeFlags
{
	G_FORMAT_SIZE_DEFAULT = 0,
	G_FORMAT_SIZE_LONG_FORMAT = 1,
	G_FORMAT_SIZE_IEC_UNITS = 2,
	G_FORMAT_SIZE_BITS = 4,
	G_FORMAT_SIZE_ONLY_VALUE = 8,
	G_FORMAT_SIZE_ONLY_UNIT = 16
}
