namespace MentorLake.Gtk4.GLib;

[Flags]
public enum GMarkupParseFlags
{
	G_MARKUP_DEFAULT_FLAGS = 0,
	G_MARKUP_DO_NOT_USE_THIS_UNSUPPORTED_FLAG = 1,
	G_MARKUP_TREAT_CDATA_AS_TEXT = 2,
	G_MARKUP_PREFIX_ERROR_POSITION = 4,
	G_MARKUP_IGNORE_QUALIFIED = 8
}
