namespace MentorLake.Gtk4.GLib;

public enum GNormalizeMode
{
	G_NORMALIZE_DEFAULT,
	G_NORMALIZE_NFD,
	G_NORMALIZE_DEFAULT_COMPOSE,
	G_NORMALIZE_NFC,
	G_NORMALIZE_ALL,
	G_NORMALIZE_NFKD,
	G_NORMALIZE_ALL_COMPOSE,
	G_NORMALIZE_NFKC
}
