namespace MentorLake.Gtk4.GLib;

[Flags]
public enum GOptionFlags
{
	G_OPTION_FLAG_NONE = 0,
	G_OPTION_FLAG_HIDDEN = 1,
	G_OPTION_FLAG_IN_MAIN = 2,
	G_OPTION_FLAG_REVERSE = 4,
	G_OPTION_FLAG_NO_ARG = 8,
	G_OPTION_FLAG_FILENAME = 16,
	G_OPTION_FLAG_OPTIONAL_ARG = 32,
	G_OPTION_FLAG_NOALIAS = 64
}
