namespace MentorLake.Gtk4.GLib;

public enum GOptionArg
{
	G_OPTION_ARG_NONE,
	G_OPTION_ARG_STRING,
	G_OPTION_ARG_INT,
	G_OPTION_ARG_CALLBACK,
	G_OPTION_ARG_FILENAME,
	G_OPTION_ARG_STRING_ARRAY,
	G_OPTION_ARG_FILENAME_ARRAY,
	G_OPTION_ARG_DOUBLE,
	G_OPTION_ARG_INT64
}
