namespace MentorLake.Gtk4.GLib;

public enum GSliceConfig
{
	G_SLICE_CONFIG_ALWAYS_MALLOC,
	G_SLICE_CONFIG_BYPASS_MAGAZINES,
	G_SLICE_CONFIG_WORKING_SET_MSECS,
	G_SLICE_CONFIG_COLOR_INCREMENT,
	G_SLICE_CONFIG_CHUNK_SIZES,
	G_SLICE_CONFIG_CONTENTION_COUNTER
}
