namespace MentorLake.Gtk4.GLib;

public enum GUriError
{
	G_URI_ERROR_FAILED,
	G_URI_ERROR_BAD_SCHEME,
	G_URI_ERROR_BAD_USER,
	G_URI_ERROR_BAD_PASSWORD,
	G_URI_ERROR_BAD_AUTH_PARAMS,
	G_URI_ERROR_BAD_HOST,
	G_URI_ERROR_BAD_PORT,
	G_URI_ERROR_BAD_PATH,
	G_URI_ERROR_BAD_QUERY,
	G_URI_ERROR_BAD_FRAGMENT
}
