namespace MentorLake.Gtk4.GLib;

public enum GUserDirectory
{
	G_USER_DIRECTORY_DESKTOP,
	G_USER_DIRECTORY_DOCUMENTS,
	G_USER_DIRECTORY_DOWNLOAD,
	G_USER_DIRECTORY_MUSIC,
	G_USER_DIRECTORY_PICTURES,
	G_USER_DIRECTORY_PUBLIC_SHARE,
	G_USER_DIRECTORY_TEMPLATES,
	G_USER_DIRECTORY_VIDEOS,
	G_USER_N_DIRECTORIES
}
