using MentorLake.Gtk4.Graphene;
using MentorLake.Gtk4.Cairo;
using MentorLake.Gtk4.Harfbuzz;
using System.Runtime.InteropServices;
using System.Reactive;
using System.Reactive.Disposables;
using System.Reactive.Linq;using MentorLake.Gtk4.GLib;
using MentorLake.Gtk4.GObject;
using MentorLake.Gtk4.Gio;
using MentorLake.Gtk4.GModule;
using MentorLake.Gtk4.Pango;
using MentorLake.Gtk4.GdkPixbuf;
using MentorLake.Gtk4.Gdk4;
using MentorLake.Gtk4.Gsk4;
using MentorLake.Gtk4.Gtk4;

namespace MentorLake.Gtk4.GLib;

public enum GVariantParseError
{
	G_VARIANT_PARSE_ERROR_FAILED,
	G_VARIANT_PARSE_ERROR_BASIC_TYPE_EXPECTED,
	G_VARIANT_PARSE_ERROR_CANNOT_INFER_TYPE,
	G_VARIANT_PARSE_ERROR_DEFINITE_TYPE_EXPECTED,
	G_VARIANT_PARSE_ERROR_INPUT_NOT_AT_END,
	G_VARIANT_PARSE_ERROR_INVALID_CHARACTER,
	G_VARIANT_PARSE_ERROR_INVALID_FORMAT_STRING,
	G_VARIANT_PARSE_ERROR_INVALID_OBJECT_PATH,
	G_VARIANT_PARSE_ERROR_INVALID_SIGNATURE,
	G_VARIANT_PARSE_ERROR_INVALID_TYPE_STRING,
	G_VARIANT_PARSE_ERROR_NO_COMMON_TYPE,
	G_VARIANT_PARSE_ERROR_NUMBER_OUT_OF_RANGE,
	G_VARIANT_PARSE_ERROR_NUMBER_TOO_BIG,
	G_VARIANT_PARSE_ERROR_TYPE_ERROR,
	G_VARIANT_PARSE_ERROR_UNEXPECTED_TOKEN,
	G_VARIANT_PARSE_ERROR_UNKNOWN_KEYWORD,
	G_VARIANT_PARSE_ERROR_UNTERMINATED_STRING_CONSTANT,
	G_VARIANT_PARSE_ERROR_VALUE_EXPECTED,
	G_VARIANT_PARSE_ERROR_RECURSION
}
