namespace MentorLake.Gtk4.GLib;

public enum GVariantClass
{
	G_VARIANT_CLASS_BOOLEAN,
	G_VARIANT_CLASS_BYTE,
	G_VARIANT_CLASS_INT16,
	G_VARIANT_CLASS_UINT16,
	G_VARIANT_CLASS_INT32,
	G_VARIANT_CLASS_UINT32,
	G_VARIANT_CLASS_INT64,
	G_VARIANT_CLASS_UINT64,
	G_VARIANT_CLASS_HANDLE,
	G_VARIANT_CLASS_DOUBLE,
	G_VARIANT_CLASS_STRING,
	G_VARIANT_CLASS_OBJECT_PATH,
	G_VARIANT_CLASS_SIGNATURE,
	G_VARIANT_CLASS_VARIANT,
	G_VARIANT_CLASS_MAYBE,
	G_VARIANT_CLASS_ARRAY,
	G_VARIANT_CLASS_TUPLE,
	G_VARIANT_CLASS_DICT_ENTRY
}
